apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: users-auth
  namespace: ecommerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: users-auth
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: JWT_SECRET
