-- +goose Up
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS x_pos DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS y_pos DOUBLE PRECISION NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE users
    DROP COLUMN IF EXISTS y_pos,
    DROP COLUMN IF EXISTS x_pos;
