run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gosimple
    - ineffassign

issues:
  exclude-files:
    - '.*_templ\.go$'
    - '.*/proto/.*\.go$'
    - '.*/database/.*\.go$'
