// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: shared/proto/inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	AvailableQty  int32                  `protobuf:"varint,2,opt,name=available_qty,json=availableQty,proto3" json:"available_qty,omitempty"`
	ReservedQty   int32                  `protobuf:"varint,3,opt,name=reserved_qty,json=reservedQty,proto3" json:"reserved_qty,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Inventory) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Inventory) GetAvailableQty() int32 {
	if x != nil {
		return x.AvailableQty
	}
	return 0
}

func (x *Inventory) GetReservedQty() int32 {
	if x != nil {
		return x.ReservedQty
	}
	return 0
}

func (x *Inventory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Inventory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	AvailableQty  int32                  `protobuf:"varint,2,opt,name=available_qty,json=availableQty,proto3" json:"available_qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryRequest) Reset() {
	*x = CreateInventoryRequest{}
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryRequest) ProtoMessage() {}

func (x *CreateInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryRequest.ProtoReflect.Descriptor instead.
func (*CreateInventoryRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInventoryRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateInventoryRequest) GetAvailableQty() int32 {
	if x != nil {
		return x.AvailableQty
	}
	return 0
}

type GetInventoryByProductIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryByProductIDRequest) Reset() {
	*x = GetInventoryByProductIDRequest{}
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryByProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryByProductIDRequest) ProtoMessage() {}

func (x *GetInventoryByProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryByProductIDRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryByProductIDRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryByProductIDRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

var File_shared_proto_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_shared_proto_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	")shared/proto/inventory/v1/inventory.proto\x12\finventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\tInventory\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\ravailable_qty\x18\x02 \x01(\x05R\favailableQty\x12!\n" +
	"\freserved_qty\x18\x03 \x01(\x05R\vreservedQty\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\\\n" +
	"\x16CreateInventoryRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\ravailable_qty\x18\x02 \x01(\x05R\favailableQty\"?\n" +
	"\x1eGetInventoryByProductIDRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId2\xc6\x01\n" +
	"\x10InventoryService\x12P\n" +
	"\x0fCreateInventory\x12$.inventory.v1.CreateInventoryRequest\x1a\x17.inventory.v1.Inventory\x12`\n" +
	"\x17GetInventoryByProductID\x12,.inventory.v1.GetInventoryByProductIDRequest\x1a\x17.inventory.v1.InventoryB?Z=refurbished-marketplace/shared/proto/inventory/v1;inventoryv1b\x06proto3"

var (
	file_shared_proto_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_shared_proto_inventory_v1_inventory_proto_rawDescData []byte
)

func file_shared_proto_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_shared_proto_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_shared_proto_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_inventory_v1_inventory_proto_rawDesc), len(file_shared_proto_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_shared_proto_inventory_v1_inventory_proto_rawDescData
}

var file_shared_proto_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shared_proto_inventory_v1_inventory_proto_goTypes = []any{
	(*Inventory)(nil),                      // 0: inventory.v1.Inventory
	(*CreateInventoryRequest)(nil),         // 1: inventory.v1.CreateInventoryRequest
	(*GetInventoryByProductIDRequest)(nil), // 2: inventory.v1.GetInventoryByProductIDRequest
	(*timestamppb.Timestamp)(nil),          // 3: google.protobuf.Timestamp
}
var file_shared_proto_inventory_v1_inventory_proto_depIdxs = []int32{
	3, // 0: inventory.v1.Inventory.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: inventory.v1.Inventory.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: inventory.v1.InventoryService.CreateInventory:input_type -> inventory.v1.CreateInventoryRequest
	2, // 3: inventory.v1.InventoryService.GetInventoryByProductID:input_type -> inventory.v1.GetInventoryByProductIDRequest
	0, // 4: inventory.v1.InventoryService.CreateInventory:output_type -> inventory.v1.Inventory
	0, // 5: inventory.v1.InventoryService.GetInventoryByProductID:output_type -> inventory.v1.Inventory
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shared_proto_inventory_v1_inventory_proto_init() }
func file_shared_proto_inventory_v1_inventory_proto_init() {
	if File_shared_proto_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_inventory_v1_inventory_proto_rawDesc), len(file_shared_proto_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_shared_proto_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_shared_proto_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_shared_proto_inventory_v1_inventory_proto = out.File
	file_shared_proto_inventory_v1_inventory_proto_goTypes = nil
	file_shared_proto_inventory_v1_inventory_proto_depIdxs = nil
}
