// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: shared/proto/inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	AvailableQty  int32                  `protobuf:"varint,2,opt,name=available_qty,json=availableQty,proto3" json:"available_qty,omitempty"`
	ReservedQty   int32                  `protobuf:"varint,3,opt,name=reserved_qty,json=reservedQty,proto3" json:"reserved_qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Stock) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Stock) GetAvailableQty() int32 {
	if x != nil {
		return x.AvailableQty
	}
	return 0
}

func (x *Stock) GetReservedQty() int32 {
	if x != nil {
		return x.ReservedQty
	}
	return 0
}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetStocksByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []string               `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStocksByIDsRequest) Reset() {
	*x = GetStocksByIDsRequest{}
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStocksByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStocksByIDsRequest) ProtoMessage() {}

func (x *GetStocksByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStocksByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetStocksByIDsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetStocksByIDsRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type GetStocksByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stocks        []*Stock               `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStocksByIDsResponse) Reset() {
	*x = GetStocksByIDsResponse{}
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStocksByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStocksByIDsResponse) ProtoMessage() {}

func (x *GetStocksByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStocksByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetStocksByIDsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetStocksByIDsResponse) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type ReserveStockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockItem) Reset() {
	*x = ReserveStockItem{}
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockItem) ProtoMessage() {}

func (x *ReserveStockItem) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockItem.ProtoReflect.Descriptor instead.
func (*ReserveStockItem) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveStockItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ReserveStockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TotalCents    int64                  `protobuf:"varint,3,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Items         []*ReserveStockItem    `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveStockRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ReserveStockRequest) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *ReserveStockRequest) GetItems() []*ReserveStockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

var File_shared_proto_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_shared_proto_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	")shared/proto/inventory/v1/inventory.proto\x12\finventory.v1\"n\n" +
	"\x05Stock\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\ravailable_qty\x18\x02 \x01(\x05R\favailableQty\x12!\n" +
	"\freserved_qty\x18\x03 \x01(\x05R\vreservedQty\"0\n" +
	"\x0fGetStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"8\n" +
	"\x15GetStocksByIDsRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds\"E\n" +
	"\x16GetStocksByIDsResponse\x12+\n" +
	"\x06stocks\x18\x01 \x03(\v2\x13.inventory.v1.StockR\x06stocks\"M\n" +
	"\x10ReserveStockItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xa8\x01\n" +
	"\x13ReserveStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vtotal_cents\x18\x03 \x01(\x03R\n" +
	"totalCents\x124\n" +
	"\x05items\x18\x04 \x03(\v2\x1e.inventory.v1.ReserveStockItemR\x05items\"\x16\n" +
	"\x14ReserveStockResponse2\x86\x02\n" +
	"\x10InventoryService\x12>\n" +
	"\bGetStock\x12\x1d.inventory.v1.GetStockRequest\x1a\x13.inventory.v1.Stock\x12[\n" +
	"\x0eGetStocksByIDs\x12#.inventory.v1.GetStocksByIDsRequest\x1a$.inventory.v1.GetStocksByIDsResponse\x12U\n" +
	"\fReserveStock\x12!.inventory.v1.ReserveStockRequest\x1a\".inventory.v1.ReserveStockResponseBXZVgithub.com/phuchoang2603/refurbished-marketplace/shared/proto/inventory/v1;inventoryv1b\x06proto3"

var (
	file_shared_proto_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_shared_proto_inventory_v1_inventory_proto_rawDescData []byte
)

func file_shared_proto_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_shared_proto_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_shared_proto_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_inventory_v1_inventory_proto_rawDesc), len(file_shared_proto_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_shared_proto_inventory_v1_inventory_proto_rawDescData
}

var file_shared_proto_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_shared_proto_inventory_v1_inventory_proto_goTypes = []any{
	(*Stock)(nil),                  // 0: inventory.v1.Stock
	(*GetStockRequest)(nil),        // 1: inventory.v1.GetStockRequest
	(*GetStocksByIDsRequest)(nil),  // 2: inventory.v1.GetStocksByIDsRequest
	(*GetStocksByIDsResponse)(nil), // 3: inventory.v1.GetStocksByIDsResponse
	(*ReserveStockItem)(nil),       // 4: inventory.v1.ReserveStockItem
	(*ReserveStockRequest)(nil),    // 5: inventory.v1.ReserveStockRequest
	(*ReserveStockResponse)(nil),   // 6: inventory.v1.ReserveStockResponse
}
var file_shared_proto_inventory_v1_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.v1.GetStocksByIDsResponse.stocks:type_name -> inventory.v1.Stock
	4, // 1: inventory.v1.ReserveStockRequest.items:type_name -> inventory.v1.ReserveStockItem
	1, // 2: inventory.v1.InventoryService.GetStock:input_type -> inventory.v1.GetStockRequest
	2, // 3: inventory.v1.InventoryService.GetStocksByIDs:input_type -> inventory.v1.GetStocksByIDsRequest
	5, // 4: inventory.v1.InventoryService.ReserveStock:input_type -> inventory.v1.ReserveStockRequest
	0, // 5: inventory.v1.InventoryService.GetStock:output_type -> inventory.v1.Stock
	3, // 6: inventory.v1.InventoryService.GetStocksByIDs:output_type -> inventory.v1.GetStocksByIDsResponse
	6, // 7: inventory.v1.InventoryService.ReserveStock:output_type -> inventory.v1.ReserveStockResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shared_proto_inventory_v1_inventory_proto_init() }
func file_shared_proto_inventory_v1_inventory_proto_init() {
	if File_shared_proto_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_inventory_v1_inventory_proto_rawDesc), len(file_shared_proto_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_shared_proto_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_shared_proto_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_shared_proto_inventory_v1_inventory_proto = out.File
	file_shared_proto_inventory_v1_inventory_proto_goTypes = nil
	file_shared_proto_inventory_v1_inventory_proto_depIdxs = nil
}
