apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-cnpg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.io/charts/
    chart: cloudnative-pg
    targetRevision: 0.28.3
    helm:
      releaseName: cnpg
  destination:
    server: https://kubernetes.default.svc
    namespace: operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
