apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-refurbished-marketplace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/phuchoang2603/refurbished-marketplace.git
    targetRevision: main
    path: infra/charts/refurbished-marketplace
    helm:
      releaseName: refurbished-marketplace
      values: |
        # Set global.imageTag to the commit SHA promoted from main.
        global:
          imageRegistry: ghcr.io/phuchoang2603/refurbished-marketplace
          imageTag: main
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
