// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: shared/proto/checkout/v1/events.proto

package checkoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FinalOrderStatus int32

const (
	FinalOrderStatus_FINAL_ORDER_STATUS_UNSPECIFIED FinalOrderStatus = 0
	FinalOrderStatus_FINAL_ORDER_STATUS_PAID        FinalOrderStatus = 1
	FinalOrderStatus_FINAL_ORDER_STATUS_FAILED      FinalOrderStatus = 2
)

// Enum value maps for FinalOrderStatus.
var (
	FinalOrderStatus_name = map[int32]string{
		0: "FINAL_ORDER_STATUS_UNSPECIFIED",
		1: "FINAL_ORDER_STATUS_PAID",
		2: "FINAL_ORDER_STATUS_FAILED",
	}
	FinalOrderStatus_value = map[string]int32{
		"FINAL_ORDER_STATUS_UNSPECIFIED": 0,
		"FINAL_ORDER_STATUS_PAID":        1,
		"FINAL_ORDER_STATUS_FAILED":      2,
	}
)

func (x FinalOrderStatus) Enum() *FinalOrderStatus {
	p := new(FinalOrderStatus)
	*p = x
	return p
}

func (x FinalOrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinalOrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_checkout_v1_events_proto_enumTypes[0].Descriptor()
}

func (FinalOrderStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_checkout_v1_events_proto_enumTypes[0]
}

func (x FinalOrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinalOrderStatus.Descriptor instead.
func (FinalOrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{0}
}

type CheckoutMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Context *MessageContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CheckoutMessage_CreateOrder
	//	*CheckoutMessage_OrderCreated
	//	*CheckoutMessage_OrderRejected
	//	*CheckoutMessage_ReserveStock
	//	*CheckoutMessage_StockReserved
	//	*CheckoutMessage_StockRejected
	//	*CheckoutMessage_CancelStock
	//	*CheckoutMessage_StockReleased
	//	*CheckoutMessage_CreatePaymentSession
	//	*CheckoutMessage_PaymentSessionReady
	//	*CheckoutMessage_PaymentSessionRejected
	//	*CheckoutMessage_CancelPaymentSession
	//	*CheckoutMessage_PaymentCancelled
	//	*CheckoutMessage_PaymentSucceeded
	//	*CheckoutMessage_PaymentFailed
	//	*CheckoutMessage_PaymentUncertain
	//	*CheckoutMessage_CommitStock
	//	*CheckoutMessage_StockCommitted
	//	*CheckoutMessage_FinalizeOrder
	//	*CheckoutMessage_OrderFinalized
	Payload       isCheckoutMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutMessage) Reset() {
	*x = CheckoutMessage{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutMessage) ProtoMessage() {}

func (x *CheckoutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutMessage.ProtoReflect.Descriptor instead.
func (*CheckoutMessage) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *CheckoutMessage) GetContext() *MessageContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CheckoutMessage) GetPayload() isCheckoutMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CheckoutMessage) GetCreateOrder() *CreateOrder {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_CreateOrder); ok {
			return x.CreateOrder
		}
	}
	return nil
}

func (x *CheckoutMessage) GetOrderCreated() *OrderCreated {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_OrderCreated); ok {
			return x.OrderCreated
		}
	}
	return nil
}

func (x *CheckoutMessage) GetOrderRejected() *OrderRejected {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_OrderRejected); ok {
			return x.OrderRejected
		}
	}
	return nil
}

func (x *CheckoutMessage) GetReserveStock() *ReserveStock {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_ReserveStock); ok {
			return x.ReserveStock
		}
	}
	return nil
}

func (x *CheckoutMessage) GetStockReserved() *StockReserved {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_StockReserved); ok {
			return x.StockReserved
		}
	}
	return nil
}

func (x *CheckoutMessage) GetStockRejected() *StockRejected {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_StockRejected); ok {
			return x.StockRejected
		}
	}
	return nil
}

func (x *CheckoutMessage) GetCancelStock() *CancelStock {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_CancelStock); ok {
			return x.CancelStock
		}
	}
	return nil
}

func (x *CheckoutMessage) GetStockReleased() *StockReleased {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_StockReleased); ok {
			return x.StockReleased
		}
	}
	return nil
}

func (x *CheckoutMessage) GetCreatePaymentSession() *CreatePaymentSession {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_CreatePaymentSession); ok {
			return x.CreatePaymentSession
		}
	}
	return nil
}

func (x *CheckoutMessage) GetPaymentSessionReady() *PaymentSessionReady {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_PaymentSessionReady); ok {
			return x.PaymentSessionReady
		}
	}
	return nil
}

func (x *CheckoutMessage) GetPaymentSessionRejected() *PaymentSessionRejected {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_PaymentSessionRejected); ok {
			return x.PaymentSessionRejected
		}
	}
	return nil
}

func (x *CheckoutMessage) GetCancelPaymentSession() *CancelPaymentSession {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_CancelPaymentSession); ok {
			return x.CancelPaymentSession
		}
	}
	return nil
}

func (x *CheckoutMessage) GetPaymentCancelled() *PaymentCancelled {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_PaymentCancelled); ok {
			return x.PaymentCancelled
		}
	}
	return nil
}

func (x *CheckoutMessage) GetPaymentSucceeded() *PaymentSucceeded {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_PaymentSucceeded); ok {
			return x.PaymentSucceeded
		}
	}
	return nil
}

func (x *CheckoutMessage) GetPaymentFailed() *PaymentFailed {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_PaymentFailed); ok {
			return x.PaymentFailed
		}
	}
	return nil
}

func (x *CheckoutMessage) GetPaymentUncertain() *PaymentUncertain {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_PaymentUncertain); ok {
			return x.PaymentUncertain
		}
	}
	return nil
}

func (x *CheckoutMessage) GetCommitStock() *CommitStock {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_CommitStock); ok {
			return x.CommitStock
		}
	}
	return nil
}

func (x *CheckoutMessage) GetStockCommitted() *StockCommitted {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_StockCommitted); ok {
			return x.StockCommitted
		}
	}
	return nil
}

func (x *CheckoutMessage) GetFinalizeOrder() *FinalizeOrder {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_FinalizeOrder); ok {
			return x.FinalizeOrder
		}
	}
	return nil
}

func (x *CheckoutMessage) GetOrderFinalized() *OrderFinalized {
	if x != nil {
		if x, ok := x.Payload.(*CheckoutMessage_OrderFinalized); ok {
			return x.OrderFinalized
		}
	}
	return nil
}

type isCheckoutMessage_Payload interface {
	isCheckoutMessage_Payload()
}

type CheckoutMessage_CreateOrder struct {
	CreateOrder *CreateOrder `protobuf:"bytes,2,opt,name=create_order,json=createOrder,proto3,oneof"`
}

type CheckoutMessage_OrderCreated struct {
	OrderCreated *OrderCreated `protobuf:"bytes,3,opt,name=order_created,json=orderCreated,proto3,oneof"`
}

type CheckoutMessage_OrderRejected struct {
	OrderRejected *OrderRejected `protobuf:"bytes,4,opt,name=order_rejected,json=orderRejected,proto3,oneof"`
}

type CheckoutMessage_ReserveStock struct {
	ReserveStock *ReserveStock `protobuf:"bytes,5,opt,name=reserve_stock,json=reserveStock,proto3,oneof"`
}

type CheckoutMessage_StockReserved struct {
	StockReserved *StockReserved `protobuf:"bytes,6,opt,name=stock_reserved,json=stockReserved,proto3,oneof"`
}

type CheckoutMessage_StockRejected struct {
	StockRejected *StockRejected `protobuf:"bytes,7,opt,name=stock_rejected,json=stockRejected,proto3,oneof"`
}

type CheckoutMessage_CancelStock struct {
	CancelStock *CancelStock `protobuf:"bytes,8,opt,name=cancel_stock,json=cancelStock,proto3,oneof"`
}

type CheckoutMessage_StockReleased struct {
	StockReleased *StockReleased `protobuf:"bytes,9,opt,name=stock_released,json=stockReleased,proto3,oneof"`
}

type CheckoutMessage_CreatePaymentSession struct {
	CreatePaymentSession *CreatePaymentSession `protobuf:"bytes,10,opt,name=create_payment_session,json=createPaymentSession,proto3,oneof"`
}

type CheckoutMessage_PaymentSessionReady struct {
	PaymentSessionReady *PaymentSessionReady `protobuf:"bytes,11,opt,name=payment_session_ready,json=paymentSessionReady,proto3,oneof"`
}

type CheckoutMessage_PaymentSessionRejected struct {
	PaymentSessionRejected *PaymentSessionRejected `protobuf:"bytes,12,opt,name=payment_session_rejected,json=paymentSessionRejected,proto3,oneof"`
}

type CheckoutMessage_CancelPaymentSession struct {
	CancelPaymentSession *CancelPaymentSession `protobuf:"bytes,13,opt,name=cancel_payment_session,json=cancelPaymentSession,proto3,oneof"`
}

type CheckoutMessage_PaymentCancelled struct {
	PaymentCancelled *PaymentCancelled `protobuf:"bytes,14,opt,name=payment_cancelled,json=paymentCancelled,proto3,oneof"`
}

type CheckoutMessage_PaymentSucceeded struct {
	PaymentSucceeded *PaymentSucceeded `protobuf:"bytes,15,opt,name=payment_succeeded,json=paymentSucceeded,proto3,oneof"`
}

type CheckoutMessage_PaymentFailed struct {
	PaymentFailed *PaymentFailed `protobuf:"bytes,16,opt,name=payment_failed,json=paymentFailed,proto3,oneof"`
}

type CheckoutMessage_PaymentUncertain struct {
	PaymentUncertain *PaymentUncertain `protobuf:"bytes,17,opt,name=payment_uncertain,json=paymentUncertain,proto3,oneof"`
}

type CheckoutMessage_CommitStock struct {
	CommitStock *CommitStock `protobuf:"bytes,18,opt,name=commit_stock,json=commitStock,proto3,oneof"`
}

type CheckoutMessage_StockCommitted struct {
	StockCommitted *StockCommitted `protobuf:"bytes,19,opt,name=stock_committed,json=stockCommitted,proto3,oneof"`
}

type CheckoutMessage_FinalizeOrder struct {
	FinalizeOrder *FinalizeOrder `protobuf:"bytes,20,opt,name=finalize_order,json=finalizeOrder,proto3,oneof"`
}

type CheckoutMessage_OrderFinalized struct {
	OrderFinalized *OrderFinalized `protobuf:"bytes,21,opt,name=order_finalized,json=orderFinalized,proto3,oneof"`
}

func (*CheckoutMessage_CreateOrder) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_OrderCreated) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_OrderRejected) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_ReserveStock) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_StockReserved) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_StockRejected) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_CancelStock) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_StockReleased) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_CreatePaymentSession) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_PaymentSessionReady) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_PaymentSessionRejected) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_CancelPaymentSession) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_PaymentCancelled) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_PaymentSucceeded) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_PaymentFailed) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_PaymentUncertain) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_CommitStock) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_StockCommitted) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_FinalizeOrder) isCheckoutMessage_Payload() {}

func (*CheckoutMessage_OrderFinalized) isCheckoutMessage_Payload() {}

type MessageContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CheckoutId      string                 `protobuf:"bytes,2,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	OperationId     string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	CausationId     string                 `protobuf:"bytes,4,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	OrderId         string                 `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	WorkflowVersion uint64                 `protobuf:"varint,6,opt,name=workflow_version,json=workflowVersion,proto3" json:"workflow_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageContext) Reset() {
	*x = MessageContext{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContext) ProtoMessage() {}

func (x *MessageContext) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContext.ProtoReflect.Descriptor instead.
func (*MessageContext) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *MessageContext) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageContext) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *MessageContext) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *MessageContext) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *MessageContext) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *MessageContext) GetWorkflowVersion() uint64 {
	if x != nil {
		return x.WorkflowVersion
	}
	return 0
}

type CheckoutLine struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity       int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int64                  `protobuf:"varint,4,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckoutLine) Reset() {
	*x = CheckoutLine{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutLine) ProtoMessage() {}

func (x *CheckoutLine) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutLine.ProtoReflect.Descriptor instead.
func (*CheckoutLine) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *CheckoutLine) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CheckoutLine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckoutLine) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CheckoutLine) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

type CheckoutAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Line1         string                 `protobuf:"bytes,2,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2         string                 `protobuf:"bytes,3,opt,name=line2,proto3" json:"line2,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutAddress) Reset() {
	*x = CheckoutAddress{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutAddress) ProtoMessage() {}

func (x *CheckoutAddress) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutAddress.ProtoReflect.Descriptor instead.
func (*CheckoutAddress) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *CheckoutAddress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckoutAddress) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *CheckoutAddress) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

func (x *CheckoutAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CheckoutAddress) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CheckoutAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CheckoutAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type CreateOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerUserId   string                 `protobuf:"bytes,1,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TotalCents    int64                  `protobuf:"varint,3,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Items         []*CheckoutLine        `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrder) Reset() {
	*x = CreateOrder{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrder) ProtoMessage() {}

func (x *CreateOrder) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrder.ProtoReflect.Descriptor instead.
func (*CreateOrder) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrder) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *CreateOrder) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateOrder) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *CreateOrder) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrder) GetItems() []*CheckoutLine {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreated) Reset() {
	*x = OrderCreated{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated) ProtoMessage() {}

func (x *OrderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated.ProtoReflect.Descriptor instead.
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{5}
}

type OrderRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRejected) Reset() {
	*x = OrderRejected{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRejected) ProtoMessage() {}

func (x *OrderRejected) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRejected.ProtoReflect.Descriptor instead.
func (*OrderRejected) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *OrderRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReserveStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TotalCents    int64                  `protobuf:"varint,2,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Items         []*CheckoutLine        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStock) Reset() {
	*x = ReserveStock{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStock) ProtoMessage() {}

func (x *ReserveStock) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStock.ProtoReflect.Descriptor instead.
func (*ReserveStock) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *ReserveStock) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ReserveStock) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *ReserveStock) GetItems() []*CheckoutLine {
	if x != nil {
		return x.Items
	}
	return nil
}

type StockReserved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockReserved) Reset() {
	*x = StockReserved{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockReserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReserved) ProtoMessage() {}

func (x *StockReserved) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReserved.ProtoReflect.Descriptor instead.
func (*StockReserved) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{8}
}

type StockRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockRejected) Reset() {
	*x = StockRejected{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockRejected) ProtoMessage() {}

func (x *StockRejected) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockRejected.ProtoReflect.Descriptor instead.
func (*StockRejected) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *StockRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelStock) Reset() {
	*x = CancelStock{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelStock) ProtoMessage() {}

func (x *CancelStock) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelStock.ProtoReflect.Descriptor instead.
func (*CancelStock) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *CancelStock) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StockReleased struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockReleased) Reset() {
	*x = StockReleased{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockReleased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReleased) ProtoMessage() {}

func (x *StockReleased) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReleased.ProtoReflect.Descriptor instead.
func (*StockReleased) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{11}
}

type CreatePaymentSession struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BuyerUserId            string                 `protobuf:"bytes,1,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	BuyerEmail             string                 `protobuf:"bytes,2,opt,name=buyer_email,json=buyerEmail,proto3" json:"buyer_email,omitempty"`
	MerchantId             string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TotalCents             int64                  `protobuf:"varint,4,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Currency               string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	ShippingAddress        *CheckoutAddress       `protobuf:"bytes,6,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Items                  []*CheckoutLine        `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	ReturnUrl              string                 `protobuf:"bytes,8,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	ReservationOperationId string                 `protobuf:"bytes,9,opt,name=reservation_operation_id,json=reservationOperationId,proto3" json:"reservation_operation_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreatePaymentSession) Reset() {
	*x = CreatePaymentSession{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentSession) ProtoMessage() {}

func (x *CreatePaymentSession) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentSession.ProtoReflect.Descriptor instead.
func (*CreatePaymentSession) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *CreatePaymentSession) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *CreatePaymentSession) GetBuyerEmail() string {
	if x != nil {
		return x.BuyerEmail
	}
	return ""
}

func (x *CreatePaymentSession) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreatePaymentSession) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *CreatePaymentSession) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentSession) GetShippingAddress() *CheckoutAddress {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *CreatePaymentSession) GetItems() []*CheckoutLine {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreatePaymentSession) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *CreatePaymentSession) GetReservationOperationId() string {
	if x != nil {
		return x.ReservationOperationId
	}
	return ""
}

type PaymentSessionReady struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentSessionId string                 `protobuf:"bytes,1,opt,name=payment_session_id,json=paymentSessionId,proto3" json:"payment_session_id,omitempty"`
	ReturnUrl        string                 `protobuf:"bytes,2,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	ExpiresAtUnixMs  int64                  `protobuf:"varint,3,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaymentSessionReady) Reset() {
	*x = PaymentSessionReady{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSessionReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSessionReady) ProtoMessage() {}

func (x *PaymentSessionReady) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSessionReady.ProtoReflect.Descriptor instead.
func (*PaymentSessionReady) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{13}
}

func (x *PaymentSessionReady) GetPaymentSessionId() string {
	if x != nil {
		return x.PaymentSessionId
	}
	return ""
}

func (x *PaymentSessionReady) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *PaymentSessionReady) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

type PaymentSessionRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentSessionRejected) Reset() {
	*x = PaymentSessionRejected{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSessionRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSessionRejected) ProtoMessage() {}

func (x *PaymentSessionRejected) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSessionRejected.ProtoReflect.Descriptor instead.
func (*PaymentSessionRejected) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{14}
}

func (x *PaymentSessionRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelPaymentSession struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentSessionId string                 `protobuf:"bytes,1,opt,name=payment_session_id,json=paymentSessionId,proto3" json:"payment_session_id,omitempty"`
	Reason           string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CancelPaymentSession) Reset() {
	*x = CancelPaymentSession{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentSession) ProtoMessage() {}

func (x *CancelPaymentSession) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentSession.ProtoReflect.Descriptor instead.
func (*CancelPaymentSession) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{15}
}

func (x *CancelPaymentSession) GetPaymentSessionId() string {
	if x != nil {
		return x.PaymentSessionId
	}
	return ""
}

func (x *CancelPaymentSession) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PaymentCancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCancelled) Reset() {
	*x = PaymentCancelled{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCancelled) ProtoMessage() {}

func (x *PaymentCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCancelled.ProtoReflect.Descriptor instead.
func (*PaymentCancelled) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{16}
}

type PaymentSucceeded struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentSessionId string                 `protobuf:"bytes,1,opt,name=payment_session_id,json=paymentSessionId,proto3" json:"payment_session_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaymentSucceeded) Reset() {
	*x = PaymentSucceeded{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSucceeded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSucceeded) ProtoMessage() {}

func (x *PaymentSucceeded) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSucceeded.ProtoReflect.Descriptor instead.
func (*PaymentSucceeded) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{17}
}

func (x *PaymentSucceeded) GetPaymentSessionId() string {
	if x != nil {
		return x.PaymentSessionId
	}
	return ""
}

type PaymentFailed struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentSessionId string                 `protobuf:"bytes,1,opt,name=payment_session_id,json=paymentSessionId,proto3" json:"payment_session_id,omitempty"`
	Reason           string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaymentFailed) Reset() {
	*x = PaymentFailed{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFailed) ProtoMessage() {}

func (x *PaymentFailed) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFailed.ProtoReflect.Descriptor instead.
func (*PaymentFailed) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{18}
}

func (x *PaymentFailed) GetPaymentSessionId() string {
	if x != nil {
		return x.PaymentSessionId
	}
	return ""
}

func (x *PaymentFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PaymentUncertain struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentSessionId string                 `protobuf:"bytes,1,opt,name=payment_session_id,json=paymentSessionId,proto3" json:"payment_session_id,omitempty"`
	Reason           string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaymentUncertain) Reset() {
	*x = PaymentUncertain{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentUncertain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentUncertain) ProtoMessage() {}

func (x *PaymentUncertain) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentUncertain.ProtoReflect.Descriptor instead.
func (*PaymentUncertain) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{19}
}

func (x *PaymentUncertain) GetPaymentSessionId() string {
	if x != nil {
		return x.PaymentSessionId
	}
	return ""
}

func (x *PaymentUncertain) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CommitStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitStock) Reset() {
	*x = CommitStock{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitStock) ProtoMessage() {}

func (x *CommitStock) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitStock.ProtoReflect.Descriptor instead.
func (*CommitStock) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{20}
}

type StockCommitted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockCommitted) Reset() {
	*x = StockCommitted{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockCommitted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockCommitted) ProtoMessage() {}

func (x *StockCommitted) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockCommitted.ProtoReflect.Descriptor instead.
func (*StockCommitted) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{21}
}

type FinalizeOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        FinalOrderStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=checkout.v1.FinalOrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeOrder) Reset() {
	*x = FinalizeOrder{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeOrder) ProtoMessage() {}

func (x *FinalizeOrder) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeOrder.ProtoReflect.Descriptor instead.
func (*FinalizeOrder) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{22}
}

func (x *FinalizeOrder) GetStatus() FinalOrderStatus {
	if x != nil {
		return x.Status
	}
	return FinalOrderStatus_FINAL_ORDER_STATUS_UNSPECIFIED
}

type OrderFinalized struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        FinalOrderStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=checkout.v1.FinalOrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFinalized) Reset() {
	*x = OrderFinalized{}
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFinalized) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFinalized) ProtoMessage() {}

func (x *OrderFinalized) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_checkout_v1_events_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFinalized.ProtoReflect.Descriptor instead.
func (*OrderFinalized) Descriptor() ([]byte, []int) {
	return file_shared_proto_checkout_v1_events_proto_rawDescGZIP(), []int{23}
}

func (x *OrderFinalized) GetStatus() FinalOrderStatus {
	if x != nil {
		return x.Status
	}
	return FinalOrderStatus_FINAL_ORDER_STATUS_UNSPECIFIED
}

var File_shared_proto_checkout_v1_events_proto protoreflect.FileDescriptor

const file_shared_proto_checkout_v1_events_proto_rawDesc = "" +
	"\n" +
	"%shared/proto/checkout/v1/events.proto\x12\vcheckout.v1\"\x9b\f\n" +
	"\x0fCheckoutMessage\x125\n" +
	"\acontext\x18\x01 \x01(\v2\x1b.checkout.v1.MessageContextR\acontext\x12=\n" +
	"\fcreate_order\x18\x02 \x01(\v2\x18.checkout.v1.CreateOrderH\x00R\vcreateOrder\x12@\n" +
	"\rorder_created\x18\x03 \x01(\v2\x19.checkout.v1.OrderCreatedH\x00R\forderCreated\x12C\n" +
	"\x0eorder_rejected\x18\x04 \x01(\v2\x1a.checkout.v1.OrderRejectedH\x00R\rorderRejected\x12@\n" +
	"\rreserve_stock\x18\x05 \x01(\v2\x19.checkout.v1.ReserveStockH\x00R\freserveStock\x12C\n" +
	"\x0estock_reserved\x18\x06 \x01(\v2\x1a.checkout.v1.StockReservedH\x00R\rstockReserved\x12C\n" +
	"\x0estock_rejected\x18\a \x01(\v2\x1a.checkout.v1.StockRejectedH\x00R\rstockRejected\x12=\n" +
	"\fcancel_stock\x18\b \x01(\v2\x18.checkout.v1.CancelStockH\x00R\vcancelStock\x12C\n" +
	"\x0estock_released\x18\t \x01(\v2\x1a.checkout.v1.StockReleasedH\x00R\rstockReleased\x12Y\n" +
	"\x16create_payment_session\x18\n" +
	" \x01(\v2!.checkout.v1.CreatePaymentSessionH\x00R\x14createPaymentSession\x12V\n" +
	"\x15payment_session_ready\x18\v \x01(\v2 .checkout.v1.PaymentSessionReadyH\x00R\x13paymentSessionReady\x12_\n" +
	"\x18payment_session_rejected\x18\f \x01(\v2#.checkout.v1.PaymentSessionRejectedH\x00R\x16paymentSessionRejected\x12Y\n" +
	"\x16cancel_payment_session\x18\r \x01(\v2!.checkout.v1.CancelPaymentSessionH\x00R\x14cancelPaymentSession\x12L\n" +
	"\x11payment_cancelled\x18\x0e \x01(\v2\x1d.checkout.v1.PaymentCancelledH\x00R\x10paymentCancelled\x12L\n" +
	"\x11payment_succeeded\x18\x0f \x01(\v2\x1d.checkout.v1.PaymentSucceededH\x00R\x10paymentSucceeded\x12C\n" +
	"\x0epayment_failed\x18\x10 \x01(\v2\x1a.checkout.v1.PaymentFailedH\x00R\rpaymentFailed\x12L\n" +
	"\x11payment_uncertain\x18\x11 \x01(\v2\x1d.checkout.v1.PaymentUncertainH\x00R\x10paymentUncertain\x12=\n" +
	"\fcommit_stock\x18\x12 \x01(\v2\x18.checkout.v1.CommitStockH\x00R\vcommitStock\x12F\n" +
	"\x0fstock_committed\x18\x13 \x01(\v2\x1b.checkout.v1.StockCommittedH\x00R\x0estockCommitted\x12C\n" +
	"\x0efinalize_order\x18\x14 \x01(\v2\x1a.checkout.v1.FinalizeOrderH\x00R\rfinalizeOrder\x12F\n" +
	"\x0forder_finalized\x18\x15 \x01(\v2\x1b.checkout.v1.OrderFinalizedH\x00R\x0eorderFinalizedB\t\n" +
	"\apayload\"\xdc\x01\n" +
	"\x0eMessageContext\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1f\n" +
	"\vcheckout_id\x18\x02 \x01(\tR\n" +
	"checkoutId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12!\n" +
	"\fcausation_id\x18\x04 \x01(\tR\vcausationId\x12\x19\n" +
	"\border_id\x18\x05 \x01(\tR\aorderId\x12)\n" +
	"\x10workflow_version\x18\x06 \x01(\x04R\x0fworkflowVersion\"\x87\x01\n" +
	"\fCheckoutLine\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x04 \x01(\x03R\x0eunitPriceCents\"\xb8\x01\n" +
	"\x0fCheckoutAddress\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05line1\x18\x02 \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\x03 \x01(\tR\x05line2\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\"\xc0\x01\n" +
	"\vCreateOrder\x12\"\n" +
	"\rbuyer_user_id\x18\x01 \x01(\tR\vbuyerUserId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vtotal_cents\x18\x03 \x01(\x03R\n" +
	"totalCents\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12/\n" +
	"\x05items\x18\x05 \x03(\v2\x19.checkout.v1.CheckoutLineR\x05items\"\x0e\n" +
	"\fOrderCreated\"'\n" +
	"\rOrderRejected\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x81\x01\n" +
	"\fReserveStock\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vtotal_cents\x18\x02 \x01(\x03R\n" +
	"totalCents\x12/\n" +
	"\x05items\x18\x03 \x03(\v2\x19.checkout.v1.CheckoutLineR\x05items\"\x0f\n" +
	"\rStockReserved\"'\n" +
	"\rStockRejected\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"%\n" +
	"\vCancelStock\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x0f\n" +
	"\rStockReleased\"\x8c\x03\n" +
	"\x14CreatePaymentSession\x12\"\n" +
	"\rbuyer_user_id\x18\x01 \x01(\tR\vbuyerUserId\x12\x1f\n" +
	"\vbuyer_email\x18\x02 \x01(\tR\n" +
	"buyerEmail\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vtotal_cents\x18\x04 \x01(\x03R\n" +
	"totalCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12G\n" +
	"\x10shipping_address\x18\x06 \x01(\v2\x1c.checkout.v1.CheckoutAddressR\x0fshippingAddress\x12/\n" +
	"\x05items\x18\a \x03(\v2\x19.checkout.v1.CheckoutLineR\x05items\x12\x1d\n" +
	"\n" +
	"return_url\x18\b \x01(\tR\treturnUrl\x128\n" +
	"\x18reservation_operation_id\x18\t \x01(\tR\x16reservationOperationId\"\x8f\x01\n" +
	"\x13PaymentSessionReady\x12,\n" +
	"\x12payment_session_id\x18\x01 \x01(\tR\x10paymentSessionId\x12\x1d\n" +
	"\n" +
	"return_url\x18\x02 \x01(\tR\treturnUrl\x12+\n" +
	"\x12expires_at_unix_ms\x18\x03 \x01(\x03R\x0fexpiresAtUnixMs\"0\n" +
	"\x16PaymentSessionRejected\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\\\n" +
	"\x14CancelPaymentSession\x12,\n" +
	"\x12payment_session_id\x18\x01 \x01(\tR\x10paymentSessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x12\n" +
	"\x10PaymentCancelled\"@\n" +
	"\x10PaymentSucceeded\x12,\n" +
	"\x12payment_session_id\x18\x01 \x01(\tR\x10paymentSessionId\"U\n" +
	"\rPaymentFailed\x12,\n" +
	"\x12payment_session_id\x18\x01 \x01(\tR\x10paymentSessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"X\n" +
	"\x10PaymentUncertain\x12,\n" +
	"\x12payment_session_id\x18\x01 \x01(\tR\x10paymentSessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\r\n" +
	"\vCommitStock\"\x10\n" +
	"\x0eStockCommitted\"F\n" +
	"\rFinalizeOrder\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.checkout.v1.FinalOrderStatusR\x06status\"G\n" +
	"\x0eOrderFinalized\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.checkout.v1.FinalOrderStatusR\x06status*r\n" +
	"\x10FinalOrderStatus\x12\"\n" +
	"\x1eFINAL_ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FINAL_ORDER_STATUS_PAID\x10\x01\x12\x1d\n" +
	"\x19FINAL_ORDER_STATUS_FAILED\x10\x02BVZTgithub.com/phuchoang2603/refurbished-marketplace/shared/proto/checkout/v1;checkoutv1b\x06proto3"

var (
	file_shared_proto_checkout_v1_events_proto_rawDescOnce sync.Once
	file_shared_proto_checkout_v1_events_proto_rawDescData []byte
)

func file_shared_proto_checkout_v1_events_proto_rawDescGZIP() []byte {
	file_shared_proto_checkout_v1_events_proto_rawDescOnce.Do(func() {
		file_shared_proto_checkout_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_checkout_v1_events_proto_rawDesc), len(file_shared_proto_checkout_v1_events_proto_rawDesc)))
	})
	return file_shared_proto_checkout_v1_events_proto_rawDescData
}

var file_shared_proto_checkout_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_proto_checkout_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_shared_proto_checkout_v1_events_proto_goTypes = []any{
	(FinalOrderStatus)(0),          // 0: checkout.v1.FinalOrderStatus
	(*CheckoutMessage)(nil),        // 1: checkout.v1.CheckoutMessage
	(*MessageContext)(nil),         // 2: checkout.v1.MessageContext
	(*CheckoutLine)(nil),           // 3: checkout.v1.CheckoutLine
	(*CheckoutAddress)(nil),        // 4: checkout.v1.CheckoutAddress
	(*CreateOrder)(nil),            // 5: checkout.v1.CreateOrder
	(*OrderCreated)(nil),           // 6: checkout.v1.OrderCreated
	(*OrderRejected)(nil),          // 7: checkout.v1.OrderRejected
	(*ReserveStock)(nil),           // 8: checkout.v1.ReserveStock
	(*StockReserved)(nil),          // 9: checkout.v1.StockReserved
	(*StockRejected)(nil),          // 10: checkout.v1.StockRejected
	(*CancelStock)(nil),            // 11: checkout.v1.CancelStock
	(*StockReleased)(nil),          // 12: checkout.v1.StockReleased
	(*CreatePaymentSession)(nil),   // 13: checkout.v1.CreatePaymentSession
	(*PaymentSessionReady)(nil),    // 14: checkout.v1.PaymentSessionReady
	(*PaymentSessionRejected)(nil), // 15: checkout.v1.PaymentSessionRejected
	(*CancelPaymentSession)(nil),   // 16: checkout.v1.CancelPaymentSession
	(*PaymentCancelled)(nil),       // 17: checkout.v1.PaymentCancelled
	(*PaymentSucceeded)(nil),       // 18: checkout.v1.PaymentSucceeded
	(*PaymentFailed)(nil),          // 19: checkout.v1.PaymentFailed
	(*PaymentUncertain)(nil),       // 20: checkout.v1.PaymentUncertain
	(*CommitStock)(nil),            // 21: checkout.v1.CommitStock
	(*StockCommitted)(nil),         // 22: checkout.v1.StockCommitted
	(*FinalizeOrder)(nil),          // 23: checkout.v1.FinalizeOrder
	(*OrderFinalized)(nil),         // 24: checkout.v1.OrderFinalized
}
var file_shared_proto_checkout_v1_events_proto_depIdxs = []int32{
	2,  // 0: checkout.v1.CheckoutMessage.context:type_name -> checkout.v1.MessageContext
	5,  // 1: checkout.v1.CheckoutMessage.create_order:type_name -> checkout.v1.CreateOrder
	6,  // 2: checkout.v1.CheckoutMessage.order_created:type_name -> checkout.v1.OrderCreated
	7,  // 3: checkout.v1.CheckoutMessage.order_rejected:type_name -> checkout.v1.OrderRejected
	8,  // 4: checkout.v1.CheckoutMessage.reserve_stock:type_name -> checkout.v1.ReserveStock
	9,  // 5: checkout.v1.CheckoutMessage.stock_reserved:type_name -> checkout.v1.StockReserved
	10, // 6: checkout.v1.CheckoutMessage.stock_rejected:type_name -> checkout.v1.StockRejected
	11, // 7: checkout.v1.CheckoutMessage.cancel_stock:type_name -> checkout.v1.CancelStock
	12, // 8: checkout.v1.CheckoutMessage.stock_released:type_name -> checkout.v1.StockReleased
	13, // 9: checkout.v1.CheckoutMessage.create_payment_session:type_name -> checkout.v1.CreatePaymentSession
	14, // 10: checkout.v1.CheckoutMessage.payment_session_ready:type_name -> checkout.v1.PaymentSessionReady
	15, // 11: checkout.v1.CheckoutMessage.payment_session_rejected:type_name -> checkout.v1.PaymentSessionRejected
	16, // 12: checkout.v1.CheckoutMessage.cancel_payment_session:type_name -> checkout.v1.CancelPaymentSession
	17, // 13: checkout.v1.CheckoutMessage.payment_cancelled:type_name -> checkout.v1.PaymentCancelled
	18, // 14: checkout.v1.CheckoutMessage.payment_succeeded:type_name -> checkout.v1.PaymentSucceeded
	19, // 15: checkout.v1.CheckoutMessage.payment_failed:type_name -> checkout.v1.PaymentFailed
	20, // 16: checkout.v1.CheckoutMessage.payment_uncertain:type_name -> checkout.v1.PaymentUncertain
	21, // 17: checkout.v1.CheckoutMessage.commit_stock:type_name -> checkout.v1.CommitStock
	22, // 18: checkout.v1.CheckoutMessage.stock_committed:type_name -> checkout.v1.StockCommitted
	23, // 19: checkout.v1.CheckoutMessage.finalize_order:type_name -> checkout.v1.FinalizeOrder
	24, // 20: checkout.v1.CheckoutMessage.order_finalized:type_name -> checkout.v1.OrderFinalized
	3,  // 21: checkout.v1.CreateOrder.items:type_name -> checkout.v1.CheckoutLine
	3,  // 22: checkout.v1.ReserveStock.items:type_name -> checkout.v1.CheckoutLine
	4,  // 23: checkout.v1.CreatePaymentSession.shipping_address:type_name -> checkout.v1.CheckoutAddress
	3,  // 24: checkout.v1.CreatePaymentSession.items:type_name -> checkout.v1.CheckoutLine
	0,  // 25: checkout.v1.FinalizeOrder.status:type_name -> checkout.v1.FinalOrderStatus
	0,  // 26: checkout.v1.OrderFinalized.status:type_name -> checkout.v1.FinalOrderStatus
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_shared_proto_checkout_v1_events_proto_init() }
func file_shared_proto_checkout_v1_events_proto_init() {
	if File_shared_proto_checkout_v1_events_proto != nil {
		return
	}
	file_shared_proto_checkout_v1_events_proto_msgTypes[0].OneofWrappers = []any{
		(*CheckoutMessage_CreateOrder)(nil),
		(*CheckoutMessage_OrderCreated)(nil),
		(*CheckoutMessage_OrderRejected)(nil),
		(*CheckoutMessage_ReserveStock)(nil),
		(*CheckoutMessage_StockReserved)(nil),
		(*CheckoutMessage_StockRejected)(nil),
		(*CheckoutMessage_CancelStock)(nil),
		(*CheckoutMessage_StockReleased)(nil),
		(*CheckoutMessage_CreatePaymentSession)(nil),
		(*CheckoutMessage_PaymentSessionReady)(nil),
		(*CheckoutMessage_PaymentSessionRejected)(nil),
		(*CheckoutMessage_CancelPaymentSession)(nil),
		(*CheckoutMessage_PaymentCancelled)(nil),
		(*CheckoutMessage_PaymentSucceeded)(nil),
		(*CheckoutMessage_PaymentFailed)(nil),
		(*CheckoutMessage_PaymentUncertain)(nil),
		(*CheckoutMessage_CommitStock)(nil),
		(*CheckoutMessage_StockCommitted)(nil),
		(*CheckoutMessage_FinalizeOrder)(nil),
		(*CheckoutMessage_OrderFinalized)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_checkout_v1_events_proto_rawDesc), len(file_shared_proto_checkout_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_checkout_v1_events_proto_goTypes,
		DependencyIndexes: file_shared_proto_checkout_v1_events_proto_depIdxs,
		EnumInfos:         file_shared_proto_checkout_v1_events_proto_enumTypes,
		MessageInfos:      file_shared_proto_checkout_v1_events_proto_msgTypes,
	}.Build()
	File_shared_proto_checkout_v1_events_proto = out.File
	file_shared_proto_checkout_v1_events_proto_goTypes = nil
	file_shared_proto_checkout_v1_events_proto_depIdxs = nil
}
