// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox_outbox.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createInventoryOutbox = `-- name: CreateInventoryOutbox :one
INSERT INTO inventory_outbox (
    id, aggregate_id, event_type, payload, tracingspancontext
)
VALUES ($1, $2, $3, $4, $5)
RETURNING inventory_outbox.id, inventory_outbox.aggregate_id, inventory_outbox.event_type, inventory_outbox.payload, inventory_outbox.publish_attempts, inventory_outbox.created_at, inventory_outbox.published_at, inventory_outbox.tracingspancontext
`

type CreateInventoryOutboxParams struct {
	ID                 uuid.UUID
	AggregateID        uuid.UUID
	EventType          string
	Payload            []byte
	Tracingspancontext string
}

func (q *Queries) CreateInventoryOutbox(ctx context.Context, arg CreateInventoryOutboxParams) (InventoryOutbox, error) {
	row := q.db.QueryRowContext(ctx, createInventoryOutbox,
		arg.ID,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Tracingspancontext,
	)
	var i InventoryOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.PublishAttempts,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Tracingspancontext,
	)
	return i, err
}

const insertInventoryInboxMessage = `-- name: InsertInventoryInboxMessage :one
INSERT INTO inventory_inbox (message_id)
VALUES ($1)
ON CONFLICT (message_id) DO NOTHING
RETURNING TRUE
`

func (q *Queries) InsertInventoryInboxMessage(ctx context.Context, messageID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, insertInventoryInboxMessage, messageID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
