// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Inventory struct {
	ProductID    uuid.UUID
	AvailableQty int32
	ReservedQty  int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type InventoryInbox struct {
	MessageID  string
	ReceivedAt time.Time
}

type InventoryOutbox struct {
	ID                 uuid.UUID
	AggregateID        uuid.UUID
	EventType          string
	Payload            []byte
	PublishAttempts    int32
	CreatedAt          time.Time
	PublishedAt        sql.NullTime
	Tracingspancontext string
}

type InventoryReservation struct {
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Description string
	PriceCents  int64
	MerchantID  uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
