// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    id,
    name,
    description,
    price_cents,
    merchant_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    products.id, products.name, products.description, products.price_cents, products.merchant_id, products.created_at, products.updated_at
`

type CreateProductParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	PriceCents  int64
	MerchantID  uuid.UUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.MerchantID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.MerchantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    products.id, products.name, products.description, products.price_cents, products.merchant_id, products.created_at, products.updated_at,
    inventory.available_qty,
    inventory.reserved_qty
FROM products
LEFT JOIN inventory ON inventory.product_id = products.id
WHERE
    id = $1
`

type GetProductByIDRow struct {
	ID           uuid.UUID
	Name         string
	Description  string
	PriceCents   int64
	MerchantID   uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	AvailableQty sql.NullInt32
	ReservedQty  sql.NullInt32
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.MerchantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableQty,
		&i.ReservedQty,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price_cents, merchant_id, created_at, updated_at
FROM products
ORDER BY
    created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.MerchantID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
