// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: shared/proto/payment/v1/payment.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentTransactionStatus int32

const (
	PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_UNSPECIFIED PaymentTransactionStatus = 0
	PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_INITIALIZED PaymentTransactionStatus = 1
	PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_SUBMITTED   PaymentTransactionStatus = 2
	PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_SUCCEEDED   PaymentTransactionStatus = 3
	PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_FAILED      PaymentTransactionStatus = 4
)

// Enum value maps for PaymentTransactionStatus.
var (
	PaymentTransactionStatus_name = map[int32]string{
		0: "PAYMENT_TRANSACTION_STATUS_UNSPECIFIED",
		1: "PAYMENT_TRANSACTION_STATUS_INITIALIZED",
		2: "PAYMENT_TRANSACTION_STATUS_SUBMITTED",
		3: "PAYMENT_TRANSACTION_STATUS_SUCCEEDED",
		4: "PAYMENT_TRANSACTION_STATUS_FAILED",
	}
	PaymentTransactionStatus_value = map[string]int32{
		"PAYMENT_TRANSACTION_STATUS_UNSPECIFIED": 0,
		"PAYMENT_TRANSACTION_STATUS_INITIALIZED": 1,
		"PAYMENT_TRANSACTION_STATUS_SUBMITTED":   2,
		"PAYMENT_TRANSACTION_STATUS_SUCCEEDED":   3,
		"PAYMENT_TRANSACTION_STATUS_FAILED":      4,
	}
)

func (x PaymentTransactionStatus) Enum() *PaymentTransactionStatus {
	p := new(PaymentTransactionStatus)
	*p = x
	return p
}

func (x PaymentTransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentTransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentTransactionStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_payment_v1_payment_proto_enumTypes[0]
}

func (x PaymentTransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentTransactionStatus.Descriptor instead.
func (PaymentTransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Line1         string                 `protobuf:"bytes,2,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2         string                 `protobuf:"bytes,3,opt,name=line2,proto3" json:"line2,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Address) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *Address) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type InitiatePaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId     string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	PaymentToken    string                 `protobuf:"bytes,3,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	BillingAddress  *Address               `protobuf:"bytes,5,opt,name=billing_address,json=billingAddress,proto3" json:"billing_address,omitempty"`
	ShippingAddress *Address               `protobuf:"bytes,6,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitiatePaymentRequest) Reset() {
	*x = InitiatePaymentRequest{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentRequest) ProtoMessage() {}

func (x *InitiatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentRequest.ProtoReflect.Descriptor instead.
func (*InitiatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *InitiatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InitiatePaymentRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *InitiatePaymentRequest) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

func (x *InitiatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *InitiatePaymentRequest) GetBillingAddress() *Address {
	if x != nil {
		return x.BillingAddress
	}
	return nil
}

func (x *InitiatePaymentRequest) GetShippingAddress() *Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

type InitiatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatePaymentResponse) Reset() {
	*x = InitiatePaymentResponse{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentResponse) ProtoMessage() {}

func (x *InitiatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentResponse.ProtoReflect.Descriptor instead.
func (*InitiatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *InitiatePaymentResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type HandleGatewayWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal transaction ID generated by payment service.
	PaymentTransactionId string `protobuf:"bytes,1,opt,name=payment_transaction_id,json=paymentTransactionId,proto3" json:"payment_transaction_id,omitempty"`
	// Gateway-specific ID for debugging/idempotency.
	GatewayTransactionId string                   `protobuf:"bytes,2,opt,name=gateway_transaction_id,json=gatewayTransactionId,proto3" json:"gateway_transaction_id,omitempty"`
	Status               PaymentTransactionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=payment.v1.PaymentTransactionStatus" json:"status,omitempty"`
	FailureReason        string                   `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HandleGatewayWebhookRequest) Reset() {
	*x = HandleGatewayWebhookRequest{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGatewayWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGatewayWebhookRequest) ProtoMessage() {}

func (x *HandleGatewayWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGatewayWebhookRequest.ProtoReflect.Descriptor instead.
func (*HandleGatewayWebhookRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *HandleGatewayWebhookRequest) GetPaymentTransactionId() string {
	if x != nil {
		return x.PaymentTransactionId
	}
	return ""
}

func (x *HandleGatewayWebhookRequest) GetGatewayTransactionId() string {
	if x != nil {
		return x.GatewayTransactionId
	}
	return ""
}

func (x *HandleGatewayWebhookRequest) GetStatus() PaymentTransactionStatus {
	if x != nil {
		return x.Status
	}
	return PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *HandleGatewayWebhookRequest) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type HandleGatewayWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleGatewayWebhookResponse) Reset() {
	*x = HandleGatewayWebhookResponse{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGatewayWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGatewayWebhookResponse) ProtoMessage() {}

func (x *HandleGatewayWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGatewayWebhookResponse.ProtoReflect.Descriptor instead.
func (*HandleGatewayWebhookResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

type GetTransactionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PaymentTransactionId string                 `protobuf:"bytes,1,opt,name=payment_transaction_id,json=paymentTransactionId,proto3" json:"payment_transaction_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionRequest) GetPaymentTransactionId() string {
	if x != nil {
		return x.PaymentTransactionId
	}
	return ""
}

type PaymentTransaction struct {
	state                protoimpl.MessageState   `protogen:"open.v1"`
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId              string                   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderItemId          string                   `protobuf:"bytes,3,opt,name=order_item_id,json=orderItemId,proto3" json:"order_item_id,omitempty"`
	MerchantId           string                   `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	AmountCents          int64                    `protobuf:"varint,5,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Currency             string                   `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status               PaymentTransactionStatus `protobuf:"varint,7,opt,name=status,proto3,enum=payment.v1.PaymentTransactionStatus" json:"status,omitempty"`
	IdempotencyKey       string                   `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	GatewayTransactionId string                   `protobuf:"bytes,9,opt,name=gateway_transaction_id,json=gatewayTransactionId,proto3" json:"gateway_transaction_id,omitempty"`
	CreatedAt            *timestamppb.Timestamp   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp   `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PaymentTransaction) Reset() {
	*x = PaymentTransaction{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentTransaction) ProtoMessage() {}

func (x *PaymentTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentTransaction.ProtoReflect.Descriptor instead.
func (*PaymentTransaction) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentTransaction) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentTransaction) GetOrderItemId() string {
	if x != nil {
		return x.OrderItemId
	}
	return ""
}

func (x *PaymentTransaction) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *PaymentTransaction) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *PaymentTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentTransaction) GetStatus() PaymentTransactionStatus {
	if x != nil {
		return x.Status
	}
	return PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *PaymentTransaction) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PaymentTransaction) GetGatewayTransactionId() string {
	if x != nil {
		return x.GatewayTransactionId
	}
	return ""
}

func (x *PaymentTransaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentTransaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_shared_proto_payment_v1_payment_proto protoreflect.FileDescriptor

const file_shared_proto_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"%shared/proto/payment/v1/payment.proto\x12\n" +
	"payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n" +
	"\aAddress\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05line1\x18\x02 \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\x03 \x01(\tR\x05line2\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\"\x96\x02\n" +
	"\x16InitiatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12#\n" +
	"\rpayment_token\x18\x03 \x01(\tR\fpaymentToken\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12<\n" +
	"\x0fbilling_address\x18\x05 \x01(\v2\x13.payment.v1.AddressR\x0ebillingAddress\x12>\n" +
	"\x10shipping_address\x18\x06 \x01(\v2\x13.payment.v1.AddressR\x0fshippingAddress\"4\n" +
	"\x17InitiatePaymentResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xee\x01\n" +
	"\x1bHandleGatewayWebhookRequest\x124\n" +
	"\x16payment_transaction_id\x18\x01 \x01(\tR\x14paymentTransactionId\x124\n" +
	"\x16gateway_transaction_id\x18\x02 \x01(\tR\x14gatewayTransactionId\x12<\n" +
	"\x06status\x18\x03 \x01(\x0e2$.payment.v1.PaymentTransactionStatusR\x06status\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason\"\x1e\n" +
	"\x1cHandleGatewayWebhookResponse\"M\n" +
	"\x15GetTransactionRequest\x124\n" +
	"\x16payment_transaction_id\x18\x01 \x01(\tR\x14paymentTransactionId\"\xd6\x03\n" +
	"\x12PaymentTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\"\n" +
	"\rorder_item_id\x18\x03 \x01(\tR\vorderItemId\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\x12!\n" +
	"\famount_cents\x18\x05 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12<\n" +
	"\x06status\x18\a \x01(\x0e2$.payment.v1.PaymentTransactionStatusR\x06status\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x124\n" +
	"\x16gateway_transaction_id\x18\t \x01(\tR\x14gatewayTransactionId\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xed\x01\n" +
	"\x18PaymentTransactionStatus\x12*\n" +
	"&PAYMENT_TRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12*\n" +
	"&PAYMENT_TRANSACTION_STATUS_INITIALIZED\x10\x01\x12(\n" +
	"$PAYMENT_TRANSACTION_STATUS_SUBMITTED\x10\x02\x12(\n" +
	"$PAYMENT_TRANSACTION_STATUS_SUCCEEDED\x10\x03\x12%\n" +
	"!PAYMENT_TRANSACTION_STATUS_FAILED\x10\x042\xac\x02\n" +
	"\x0ePaymentService\x12Z\n" +
	"\x0fInitiatePayment\x12\".payment.v1.InitiatePaymentRequest\x1a#.payment.v1.InitiatePaymentResponse\x12i\n" +
	"\x14HandleGatewayWebhook\x12'.payment.v1.HandleGatewayWebhookRequest\x1a(.payment.v1.HandleGatewayWebhookResponse\x12S\n" +
	"\x0eGetTransaction\x12!.payment.v1.GetTransactionRequest\x1a\x1e.payment.v1.PaymentTransactionB;Z9refurbished-marketplace/shared/proto/payment/v1;paymentv1b\x06proto3"

var (
	file_shared_proto_payment_v1_payment_proto_rawDescOnce sync.Once
	file_shared_proto_payment_v1_payment_proto_rawDescData []byte
)

func file_shared_proto_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_shared_proto_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_shared_proto_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_payment_v1_payment_proto_rawDesc), len(file_shared_proto_payment_v1_payment_proto_rawDesc)))
	})
	return file_shared_proto_payment_v1_payment_proto_rawDescData
}

var file_shared_proto_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_proto_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_shared_proto_payment_v1_payment_proto_goTypes = []any{
	(PaymentTransactionStatus)(0),        // 0: payment.v1.PaymentTransactionStatus
	(*Address)(nil),                      // 1: payment.v1.Address
	(*InitiatePaymentRequest)(nil),       // 2: payment.v1.InitiatePaymentRequest
	(*InitiatePaymentResponse)(nil),      // 3: payment.v1.InitiatePaymentResponse
	(*HandleGatewayWebhookRequest)(nil),  // 4: payment.v1.HandleGatewayWebhookRequest
	(*HandleGatewayWebhookResponse)(nil), // 5: payment.v1.HandleGatewayWebhookResponse
	(*GetTransactionRequest)(nil),        // 6: payment.v1.GetTransactionRequest
	(*PaymentTransaction)(nil),           // 7: payment.v1.PaymentTransaction
	(*timestamppb.Timestamp)(nil),        // 8: google.protobuf.Timestamp
}
var file_shared_proto_payment_v1_payment_proto_depIdxs = []int32{
	1, // 0: payment.v1.InitiatePaymentRequest.billing_address:type_name -> payment.v1.Address
	1, // 1: payment.v1.InitiatePaymentRequest.shipping_address:type_name -> payment.v1.Address
	0, // 2: payment.v1.HandleGatewayWebhookRequest.status:type_name -> payment.v1.PaymentTransactionStatus
	0, // 3: payment.v1.PaymentTransaction.status:type_name -> payment.v1.PaymentTransactionStatus
	8, // 4: payment.v1.PaymentTransaction.created_at:type_name -> google.protobuf.Timestamp
	8, // 5: payment.v1.PaymentTransaction.updated_at:type_name -> google.protobuf.Timestamp
	2, // 6: payment.v1.PaymentService.InitiatePayment:input_type -> payment.v1.InitiatePaymentRequest
	4, // 7: payment.v1.PaymentService.HandleGatewayWebhook:input_type -> payment.v1.HandleGatewayWebhookRequest
	6, // 8: payment.v1.PaymentService.GetTransaction:input_type -> payment.v1.GetTransactionRequest
	3, // 9: payment.v1.PaymentService.InitiatePayment:output_type -> payment.v1.InitiatePaymentResponse
	5, // 10: payment.v1.PaymentService.HandleGatewayWebhook:output_type -> payment.v1.HandleGatewayWebhookResponse
	7, // 11: payment.v1.PaymentService.GetTransaction:output_type -> payment.v1.PaymentTransaction
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_shared_proto_payment_v1_payment_proto_init() }
func file_shared_proto_payment_v1_payment_proto_init() {
	if File_shared_proto_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_payment_v1_payment_proto_rawDesc), len(file_shared_proto_payment_v1_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_shared_proto_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_shared_proto_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_shared_proto_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_shared_proto_payment_v1_payment_proto = out.File
	file_shared_proto_payment_v1_payment_proto_goTypes = nil
	file_shared_proto_payment_v1_payment_proto_depIdxs = nil
}
