// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: shared/proto/payment/v1/payment.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostedPaymentSessionStatus int32

const (
	HostedPaymentSessionStatus_HOSTED_PAYMENT_SESSION_STATUS_UNSPECIFIED HostedPaymentSessionStatus = 0
	HostedPaymentSessionStatus_HOSTED_PAYMENT_SESSION_STATUS_PENDING     HostedPaymentSessionStatus = 1
	HostedPaymentSessionStatus_HOSTED_PAYMENT_SESSION_STATUS_SUCCEEDED   HostedPaymentSessionStatus = 2
	HostedPaymentSessionStatus_HOSTED_PAYMENT_SESSION_STATUS_FAILED      HostedPaymentSessionStatus = 3
	HostedPaymentSessionStatus_HOSTED_PAYMENT_SESSION_STATUS_EXPIRED     HostedPaymentSessionStatus = 4
)

// Enum value maps for HostedPaymentSessionStatus.
var (
	HostedPaymentSessionStatus_name = map[int32]string{
		0: "HOSTED_PAYMENT_SESSION_STATUS_UNSPECIFIED",
		1: "HOSTED_PAYMENT_SESSION_STATUS_PENDING",
		2: "HOSTED_PAYMENT_SESSION_STATUS_SUCCEEDED",
		3: "HOSTED_PAYMENT_SESSION_STATUS_FAILED",
		4: "HOSTED_PAYMENT_SESSION_STATUS_EXPIRED",
	}
	HostedPaymentSessionStatus_value = map[string]int32{
		"HOSTED_PAYMENT_SESSION_STATUS_UNSPECIFIED": 0,
		"HOSTED_PAYMENT_SESSION_STATUS_PENDING":     1,
		"HOSTED_PAYMENT_SESSION_STATUS_SUCCEEDED":   2,
		"HOSTED_PAYMENT_SESSION_STATUS_FAILED":      3,
		"HOSTED_PAYMENT_SESSION_STATUS_EXPIRED":     4,
	}
)

func (x HostedPaymentSessionStatus) Enum() *HostedPaymentSessionStatus {
	p := new(HostedPaymentSessionStatus)
	*p = x
	return p
}

func (x HostedPaymentSessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostedPaymentSessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (HostedPaymentSessionStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_payment_v1_payment_proto_enumTypes[0]
}

func (x HostedPaymentSessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostedPaymentSessionStatus.Descriptor instead.
func (HostedPaymentSessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Line1         string                 `protobuf:"bytes,2,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2         string                 `protobuf:"bytes,3,opt,name=line2,proto3" json:"line2,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Address) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *Address) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type HostedPaymentLineItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity       int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int64                  `protobuf:"varint,3,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostedPaymentLineItem) Reset() {
	*x = HostedPaymentLineItem{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostedPaymentLineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostedPaymentLineItem) ProtoMessage() {}

func (x *HostedPaymentLineItem) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostedPaymentLineItem.ProtoReflect.Descriptor instead.
func (*HostedPaymentLineItem) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *HostedPaymentLineItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *HostedPaymentLineItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *HostedPaymentLineItem) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

type CreateHostedPaymentSessionRequest struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	OrderId         string                   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId     string                   `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	Currency        string                   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	ShippingAddress *Address                 `protobuf:"bytes,4,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	ReturnUrl       string                   `protobuf:"bytes,5,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	MerchantId      string                   `protobuf:"bytes,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TotalCents      int64                    `protobuf:"varint,7,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Items           []*HostedPaymentLineItem `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateHostedPaymentSessionRequest) Reset() {
	*x = CreateHostedPaymentSessionRequest{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHostedPaymentSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostedPaymentSessionRequest) ProtoMessage() {}

func (x *CreateHostedPaymentSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostedPaymentSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateHostedPaymentSessionRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHostedPaymentSessionRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateHostedPaymentSessionRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *CreateHostedPaymentSessionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateHostedPaymentSessionRequest) GetShippingAddress() *Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *CreateHostedPaymentSessionRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *CreateHostedPaymentSessionRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateHostedPaymentSessionRequest) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *CreateHostedPaymentSessionRequest) GetItems() []*HostedPaymentLineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateHostedPaymentSessionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentSessionId string                 `protobuf:"bytes,2,opt,name=payment_session_id,json=paymentSessionId,proto3" json:"payment_session_id,omitempty"`
	ReturnUrl        string                 `protobuf:"bytes,3,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateHostedPaymentSessionResponse) Reset() {
	*x = CreateHostedPaymentSessionResponse{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHostedPaymentSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostedPaymentSessionResponse) ProtoMessage() {}

func (x *CreateHostedPaymentSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostedPaymentSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateHostedPaymentSessionResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateHostedPaymentSessionResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateHostedPaymentSessionResponse) GetPaymentSessionId() string {
	if x != nil {
		return x.PaymentSessionId
	}
	return ""
}

func (x *CreateHostedPaymentSessionResponse) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

type GetHostedPaymentSessionByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostedPaymentSessionByOrderRequest) Reset() {
	*x = GetHostedPaymentSessionByOrderRequest{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostedPaymentSessionByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostedPaymentSessionByOrderRequest) ProtoMessage() {}

func (x *GetHostedPaymentSessionByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostedPaymentSessionByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetHostedPaymentSessionByOrderRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetHostedPaymentSessionByOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type HostedPaymentSession struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        HostedPaymentSessionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=payment.v1.HostedPaymentSessionStatus" json:"status,omitempty"`
	FailureReason string                     `protobuf:"bytes,2,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostedPaymentSession) Reset() {
	*x = HostedPaymentSession{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostedPaymentSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostedPaymentSession) ProtoMessage() {}

func (x *HostedPaymentSession) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostedPaymentSession.ProtoReflect.Descriptor instead.
func (*HostedPaymentSession) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *HostedPaymentSession) GetStatus() HostedPaymentSessionStatus {
	if x != nil {
		return x.Status
	}
	return HostedPaymentSessionStatus_HOSTED_PAYMENT_SESSION_STATUS_UNSPECIFIED
}

func (x *HostedPaymentSession) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type HandleGatewayWebhookRequest struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	OrderId          string                     `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentSessionId string                     `protobuf:"bytes,2,opt,name=payment_session_id,json=paymentSessionId,proto3" json:"payment_session_id,omitempty"`
	Status           HostedPaymentSessionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=payment.v1.HostedPaymentSessionStatus" json:"status,omitempty"`
	FailureReason    string                     `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandleGatewayWebhookRequest) Reset() {
	*x = HandleGatewayWebhookRequest{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGatewayWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGatewayWebhookRequest) ProtoMessage() {}

func (x *HandleGatewayWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGatewayWebhookRequest.ProtoReflect.Descriptor instead.
func (*HandleGatewayWebhookRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *HandleGatewayWebhookRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *HandleGatewayWebhookRequest) GetPaymentSessionId() string {
	if x != nil {
		return x.PaymentSessionId
	}
	return ""
}

func (x *HandleGatewayWebhookRequest) GetStatus() HostedPaymentSessionStatus {
	if x != nil {
		return x.Status
	}
	return HostedPaymentSessionStatus_HOSTED_PAYMENT_SESSION_STATUS_UNSPECIFIED
}

func (x *HandleGatewayWebhookRequest) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type HandleGatewayWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleGatewayWebhookResponse) Reset() {
	*x = HandleGatewayWebhookResponse{}
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGatewayWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGatewayWebhookResponse) ProtoMessage() {}

func (x *HandleGatewayWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGatewayWebhookResponse.ProtoReflect.Descriptor instead.
func (*HandleGatewayWebhookResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

var File_shared_proto_payment_v1_payment_proto protoreflect.FileDescriptor

const file_shared_proto_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"%shared/proto/payment/v1/payment.proto\x12\n" +
	"payment.v1\"\xb0\x01\n" +
	"\aAddress\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05line1\x18\x02 \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\x03 \x01(\tR\x05line2\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\"|\n" +
	"\x15HostedPaymentLineItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x03 \x01(\x03R\x0eunitPriceCents\"\xd8\x02\n" +
	"!CreateHostedPaymentSessionRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12>\n" +
	"\x10shipping_address\x18\x04 \x01(\v2\x13.payment.v1.AddressR\x0fshippingAddress\x12\x1d\n" +
	"\n" +
	"return_url\x18\x05 \x01(\tR\treturnUrl\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vtotal_cents\x18\a \x01(\x03R\n" +
	"totalCents\x127\n" +
	"\x05items\x18\b \x03(\v2!.payment.v1.HostedPaymentLineItemR\x05items\"\x8c\x01\n" +
	"\"CreateHostedPaymentSessionResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12,\n" +
	"\x12payment_session_id\x18\x02 \x01(\tR\x10paymentSessionId\x12\x1d\n" +
	"\n" +
	"return_url\x18\x03 \x01(\tR\treturnUrl\"B\n" +
	"%GetHostedPaymentSessionByOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"}\n" +
	"\x14HostedPaymentSession\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.payment.v1.HostedPaymentSessionStatusR\x06status\x12%\n" +
	"\x0efailure_reason\x18\x02 \x01(\tR\rfailureReason\"\xcd\x01\n" +
	"\x1bHandleGatewayWebhookRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12,\n" +
	"\x12payment_session_id\x18\x02 \x01(\tR\x10paymentSessionId\x12>\n" +
	"\x06status\x18\x03 \x01(\x0e2&.payment.v1.HostedPaymentSessionStatusR\x06status\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason\"\x1e\n" +
	"\x1cHandleGatewayWebhookResponse*\xf8\x01\n" +
	"\x1aHostedPaymentSessionStatus\x12-\n" +
	")HOSTED_PAYMENT_SESSION_STATUS_UNSPECIFIED\x10\x00\x12)\n" +
	"%HOSTED_PAYMENT_SESSION_STATUS_PENDING\x10\x01\x12+\n" +
	"'HOSTED_PAYMENT_SESSION_STATUS_SUCCEEDED\x10\x02\x12(\n" +
	"$HOSTED_PAYMENT_SESSION_STATUS_FAILED\x10\x03\x12)\n" +
	"%HOSTED_PAYMENT_SESSION_STATUS_EXPIRED\x10\x042\xef\x02\n" +
	"\x0ePaymentService\x12{\n" +
	"\x1aCreateHostedPaymentSession\x12-.payment.v1.CreateHostedPaymentSessionRequest\x1a..payment.v1.CreateHostedPaymentSessionResponse\x12u\n" +
	"\x1eGetHostedPaymentSessionByOrder\x121.payment.v1.GetHostedPaymentSessionByOrderRequest\x1a .payment.v1.HostedPaymentSession\x12i\n" +
	"\x14HandleGatewayWebhook\x12'.payment.v1.HandleGatewayWebhookRequest\x1a(.payment.v1.HandleGatewayWebhookResponseBTZRgithub.com/phuchoang2603/refurbished-marketplace/shared/proto/payment/v1;paymentv1b\x06proto3"

var (
	file_shared_proto_payment_v1_payment_proto_rawDescOnce sync.Once
	file_shared_proto_payment_v1_payment_proto_rawDescData []byte
)

func file_shared_proto_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_shared_proto_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_shared_proto_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_payment_v1_payment_proto_rawDesc), len(file_shared_proto_payment_v1_payment_proto_rawDesc)))
	})
	return file_shared_proto_payment_v1_payment_proto_rawDescData
}

var file_shared_proto_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_proto_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shared_proto_payment_v1_payment_proto_goTypes = []any{
	(HostedPaymentSessionStatus)(0),               // 0: payment.v1.HostedPaymentSessionStatus
	(*Address)(nil),                               // 1: payment.v1.Address
	(*HostedPaymentLineItem)(nil),                 // 2: payment.v1.HostedPaymentLineItem
	(*CreateHostedPaymentSessionRequest)(nil),     // 3: payment.v1.CreateHostedPaymentSessionRequest
	(*CreateHostedPaymentSessionResponse)(nil),    // 4: payment.v1.CreateHostedPaymentSessionResponse
	(*GetHostedPaymentSessionByOrderRequest)(nil), // 5: payment.v1.GetHostedPaymentSessionByOrderRequest
	(*HostedPaymentSession)(nil),                  // 6: payment.v1.HostedPaymentSession
	(*HandleGatewayWebhookRequest)(nil),           // 7: payment.v1.HandleGatewayWebhookRequest
	(*HandleGatewayWebhookResponse)(nil),          // 8: payment.v1.HandleGatewayWebhookResponse
}
var file_shared_proto_payment_v1_payment_proto_depIdxs = []int32{
	1, // 0: payment.v1.CreateHostedPaymentSessionRequest.shipping_address:type_name -> payment.v1.Address
	2, // 1: payment.v1.CreateHostedPaymentSessionRequest.items:type_name -> payment.v1.HostedPaymentLineItem
	0, // 2: payment.v1.HostedPaymentSession.status:type_name -> payment.v1.HostedPaymentSessionStatus
	0, // 3: payment.v1.HandleGatewayWebhookRequest.status:type_name -> payment.v1.HostedPaymentSessionStatus
	3, // 4: payment.v1.PaymentService.CreateHostedPaymentSession:input_type -> payment.v1.CreateHostedPaymentSessionRequest
	5, // 5: payment.v1.PaymentService.GetHostedPaymentSessionByOrder:input_type -> payment.v1.GetHostedPaymentSessionByOrderRequest
	7, // 6: payment.v1.PaymentService.HandleGatewayWebhook:input_type -> payment.v1.HandleGatewayWebhookRequest
	4, // 7: payment.v1.PaymentService.CreateHostedPaymentSession:output_type -> payment.v1.CreateHostedPaymentSessionResponse
	6, // 8: payment.v1.PaymentService.GetHostedPaymentSessionByOrder:output_type -> payment.v1.HostedPaymentSession
	8, // 9: payment.v1.PaymentService.HandleGatewayWebhook:output_type -> payment.v1.HandleGatewayWebhookResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shared_proto_payment_v1_payment_proto_init() }
func file_shared_proto_payment_v1_payment_proto_init() {
	if File_shared_proto_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_payment_v1_payment_proto_rawDesc), len(file_shared_proto_payment_v1_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_shared_proto_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_shared_proto_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_shared_proto_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_shared_proto_payment_v1_payment_proto = out.File
	file_shared_proto_payment_v1_payment_proto_goTypes = nil
	file_shared_proto_payment_v1_payment_proto_depIdxs = nil
}
