// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: shared/proto/orders/v1/orders.proto

package ordersv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_PAID        OrderStatus = 2
	OrderStatus_ORDER_STATUS_FAILED      OrderStatus = 3
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_PAID",
		3: "ORDER_STATUS_FAILED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_PAID":        2,
		"ORDER_STATUS_FAILED":      3,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_orders_v1_orders_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_orders_v1_orders_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_orders_v1_orders_proto_rawDescGZIP(), []int{0}
}

type OrderItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId        string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId      string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity       int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int64                  `protobuf:"varint,5,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	LineTotalCents int64                  `protobuf:"varint,6,opt,name=line_total_cents,json=lineTotalCents,proto3" json:"line_total_cents,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_shared_proto_orders_v1_orders_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderItem) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

func (x *OrderItem) GetLineTotalCents() int64 {
	if x != nil {
		return x.LineTotalCents
	}
	return 0
}

func (x *OrderItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=orders.v1.OrderStatus" json:"status,omitempty"`
	TotalCents    int64                  `protobuf:"varint,4,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_shared_proto_orders_v1_orders_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateOrderItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity       int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int64                  `protobuf:"varint,3,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderItem) Reset() {
	*x = CreateOrderItem{}
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderItem) ProtoMessage() {}

func (x *CreateOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderItem.ProtoReflect.Descriptor instead.
func (*CreateOrderItem) Descriptor() ([]byte, []int) {
	return file_shared_proto_orders_v1_orders_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderItem) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerUserId   string                 `protobuf:"bytes,1,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	Items         []*CreateOrderItem     `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalCents    int64                  `protobuf:"varint,3,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_orders_v1_orders_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*CreateOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

type GetOrderByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDRequest) Reset() {
	*x = GetOrderByIDRequest{}
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDRequest) ProtoMessage() {}

func (x *GetOrderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIDRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_orders_v1_orders_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListOrdersByBuyerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerUserId   string                 `protobuf:"bytes,1,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersByBuyerRequest) Reset() {
	*x = ListOrdersByBuyerRequest{}
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersByBuyerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersByBuyerRequest) ProtoMessage() {}

func (x *ListOrdersByBuyerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersByBuyerRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersByBuyerRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_orders_v1_orders_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersByBuyerRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *ListOrdersByBuyerRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersByBuyerRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListOrdersByBuyerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersByBuyerResponse) Reset() {
	*x = ListOrdersByBuyerResponse{}
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersByBuyerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersByBuyerResponse) ProtoMessage() {}

func (x *ListOrdersByBuyerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersByBuyerResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersByBuyerResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_orders_v1_orders_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrdersByBuyerResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=orders.v1.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_orders_v1_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_orders_v1_orders_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrderStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

var File_shared_proto_orders_v1_orders_proto protoreflect.FileDescriptor

const file_shared_proto_orders_v1_orders_proto_rawDesc = "" +
	"\n" +
	"#shared/proto/orders/v1/orders.proto\x12\torders.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x02\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x05 \x01(\x03R\x0eunitPriceCents\x12(\n" +
	"\x10line_total_cents\x18\x06 \x01(\x03R\x0elineTotalCents\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xae\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.orders.v1.OrderStatusR\x06status\x12\x1f\n" +
	"\vtotal_cents\x18\x04 \x01(\x03R\n" +
	"totalCents\x12*\n" +
	"\x05items\x18\x05 \x03(\v2\x14.orders.v1.OrderItemR\x05items\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"v\n" +
	"\x0fCreateOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x03 \x01(\x03R\x0eunitPriceCents\"\x8b\x01\n" +
	"\x12CreateOrderRequest\x12\"\n" +
	"\rbuyer_user_id\x18\x01 \x01(\tR\vbuyerUserId\x120\n" +
	"\x05items\x18\x02 \x03(\v2\x1a.orders.v1.CreateOrderItemR\x05items\x12\x1f\n" +
	"\vtotal_cents\x18\x03 \x01(\x03R\n" +
	"totalCents\"%\n" +
	"\x13GetOrderByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"l\n" +
	"\x18ListOrdersByBuyerRequest\x12\"\n" +
	"\rbuyer_user_id\x18\x01 \x01(\tR\vbuyerUserId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"E\n" +
	"\x19ListOrdersByBuyerResponse\x12(\n" +
	"\x06orders\x18\x01 \x03(\v2\x10.orders.v1.OrderR\x06orders\"Z\n" +
	"\x18UpdateOrderStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.orders.v1.OrderStatusR\x06status*u\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x02\x12\x17\n" +
	"\x13ORDER_STATUS_FAILED\x10\x032\xbd\x02\n" +
	"\rOrdersService\x12>\n" +
	"\vCreateOrder\x12\x1d.orders.v1.CreateOrderRequest\x1a\x10.orders.v1.Order\x12@\n" +
	"\fGetOrderByID\x12\x1e.orders.v1.GetOrderByIDRequest\x1a\x10.orders.v1.Order\x12^\n" +
	"\x11ListOrdersByBuyer\x12#.orders.v1.ListOrdersByBuyerRequest\x1a$.orders.v1.ListOrdersByBuyerResponse\x12J\n" +
	"\x11UpdateOrderStatus\x12#.orders.v1.UpdateOrderStatusRequest\x1a\x10.orders.v1.OrderB9Z7refurbished-marketplace/shared/proto/orders/v1;ordersv1b\x06proto3"

var (
	file_shared_proto_orders_v1_orders_proto_rawDescOnce sync.Once
	file_shared_proto_orders_v1_orders_proto_rawDescData []byte
)

func file_shared_proto_orders_v1_orders_proto_rawDescGZIP() []byte {
	file_shared_proto_orders_v1_orders_proto_rawDescOnce.Do(func() {
		file_shared_proto_orders_v1_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_orders_v1_orders_proto_rawDesc), len(file_shared_proto_orders_v1_orders_proto_rawDesc)))
	})
	return file_shared_proto_orders_v1_orders_proto_rawDescData
}

var file_shared_proto_orders_v1_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_proto_orders_v1_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shared_proto_orders_v1_orders_proto_goTypes = []any{
	(OrderStatus)(0),                  // 0: orders.v1.OrderStatus
	(*OrderItem)(nil),                 // 1: orders.v1.OrderItem
	(*Order)(nil),                     // 2: orders.v1.Order
	(*CreateOrderItem)(nil),           // 3: orders.v1.CreateOrderItem
	(*CreateOrderRequest)(nil),        // 4: orders.v1.CreateOrderRequest
	(*GetOrderByIDRequest)(nil),       // 5: orders.v1.GetOrderByIDRequest
	(*ListOrdersByBuyerRequest)(nil),  // 6: orders.v1.ListOrdersByBuyerRequest
	(*ListOrdersByBuyerResponse)(nil), // 7: orders.v1.ListOrdersByBuyerResponse
	(*UpdateOrderStatusRequest)(nil),  // 8: orders.v1.UpdateOrderStatusRequest
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_shared_proto_orders_v1_orders_proto_depIdxs = []int32{
	9,  // 0: orders.v1.OrderItem.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: orders.v1.Order.status:type_name -> orders.v1.OrderStatus
	1,  // 2: orders.v1.Order.items:type_name -> orders.v1.OrderItem
	9,  // 3: orders.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	9,  // 4: orders.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 5: orders.v1.CreateOrderRequest.items:type_name -> orders.v1.CreateOrderItem
	2,  // 6: orders.v1.ListOrdersByBuyerResponse.orders:type_name -> orders.v1.Order
	0,  // 7: orders.v1.UpdateOrderStatusRequest.status:type_name -> orders.v1.OrderStatus
	4,  // 8: orders.v1.OrdersService.CreateOrder:input_type -> orders.v1.CreateOrderRequest
	5,  // 9: orders.v1.OrdersService.GetOrderByID:input_type -> orders.v1.GetOrderByIDRequest
	6,  // 10: orders.v1.OrdersService.ListOrdersByBuyer:input_type -> orders.v1.ListOrdersByBuyerRequest
	8,  // 11: orders.v1.OrdersService.UpdateOrderStatus:input_type -> orders.v1.UpdateOrderStatusRequest
	2,  // 12: orders.v1.OrdersService.CreateOrder:output_type -> orders.v1.Order
	2,  // 13: orders.v1.OrdersService.GetOrderByID:output_type -> orders.v1.Order
	7,  // 14: orders.v1.OrdersService.ListOrdersByBuyer:output_type -> orders.v1.ListOrdersByBuyerResponse
	2,  // 15: orders.v1.OrdersService.UpdateOrderStatus:output_type -> orders.v1.Order
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_shared_proto_orders_v1_orders_proto_init() }
func file_shared_proto_orders_v1_orders_proto_init() {
	if File_shared_proto_orders_v1_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_orders_v1_orders_proto_rawDesc), len(file_shared_proto_orders_v1_orders_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_orders_v1_orders_proto_goTypes,
		DependencyIndexes: file_shared_proto_orders_v1_orders_proto_depIdxs,
		EnumInfos:         file_shared_proto_orders_v1_orders_proto_enumTypes,
		MessageInfos:      file_shared_proto_orders_v1_orders_proto_msgTypes,
	}.Build()
	File_shared_proto_orders_v1_orders_proto = out.File
	file_shared_proto_orders_v1_orders_proto_goTypes = nil
	file_shared_proto_orders_v1_orders_proto_depIdxs = nil
}
