global:
  imagePullPolicy: IfNotPresent
  imageRegistry: ""
  imageTag: ""

externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler

services:
  web:
    enabled: true
    image: web
    port: 8080
    auth:
      secretName: users-auth
      secretKey: JWT_SECRET
    env:
      USERS_SVC_ADDR: users:9091
      PRODUCTS_SVC_ADDR: products:9092
      ORDERS_SVC_ADDR: orders:9093
      CART_SVC_ADDR: cart:9094
      PAYMENT_SVC_ADDR: payment:9096
      HOSTED_PAYMENT_BASE_URL: http://localhost:8097

  users:
    enabled: true
    image: users
    port: 9091
    auth:
      secretName: users-auth
      secretKey: JWT_SECRET
    migration:
      enabled: true
      image: users-migrator
    db:
      host: users-db-rw
      port: 5432
      name: users_db
      owner: users_app
      secretName: users-app
      usernameKey: username
      passwordKey: password
      instances: 1
      storageSize: 1Gi

  products:
    enabled: true
    image: products
    port: 9092
    env:
      KAFKA_BOOTSTRAP_SERVERS: ecommerce-kafka-cluster-kafka-bootstrap:9092
    migration:
      enabled: true
      image: products-migrator
    db:
      host: products-db-rw
      port: 5432
      name: products_db
      owner: products_app
      secretName: products-app
      usernameKey: username
      passwordKey: password
      instances: 1
      storageSize: 1Gi

  orders:
    enabled: true
    image: orders
    port: 9093
    env:
      KAFKA_BOOTSTRAP_SERVERS: ecommerce-kafka-cluster-kafka-bootstrap:9092
    migration:
      enabled: true
      image: orders-migrator
    db:
      host: orders-db-rw
      port: 5432
      name: orders_db
      owner: orders_app
      secretName: orders-app
      usernameKey: username
      passwordKey: password
      instances: 1
      storageSize: 1Gi

  cart:
    enabled: true
    image: cart
    port: 9094
    env:
      REDIS_ADDR: 127.0.0.1:6379
  payment:
    enabled: true
    image: payment
    port: 9096
    env:
      KAFKA_BOOTSTRAP_SERVERS: ecommerce-kafka-cluster-kafka-bootstrap:9092
    migration:
      enabled: true
      image: payment-migrator
    db:
      host: payment-db-rw
      port: 5432
      name: payment_db
      owner: payment_app
      secretName: payment-app
      usernameKey: username
      passwordKey: password
      instances: 1
      storageSize: 1Gi

  payment-gateway-simulator:
    enabled: true
    image: payment-gateway-simulator
    port: 8097
