// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: shared/proto/search/v1/search.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_shared_proto_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProductsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *SearchProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchProductsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListingHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceCents    int64                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	MerchantId    string                 `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingHit) Reset() {
	*x = ListingHit{}
	mi := &file_shared_proto_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingHit) ProtoMessage() {}

func (x *ListingHit) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingHit.ProtoReflect.Descriptor instead.
func (*ListingHit) Descriptor() ([]byte, []int) {
	return file_shared_proto_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *ListingHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingHit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListingHit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingHit) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *ListingHit) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListingHit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SearchProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*ListingHit          `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResponse) Reset() {
	*x = SearchProductsResponse{}
	mi := &file_shared_proto_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResponse) ProtoMessage() {}

func (x *SearchProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResponse.ProtoReflect.Descriptor instead.
func (*SearchProductsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchProductsResponse) GetListings() []*ListingHit {
	if x != nil {
		return x.Listings
	}
	return nil
}

var File_shared_proto_search_v1_search_proto protoreflect.FileDescriptor

const file_shared_proto_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"#shared/proto/search/v1/search.proto\x12\tsearch.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n" +
	"\x15SearchProductsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xcf\x01\n" +
	"\n" +
	"ListingHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\tR\n" +
	"merchantId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"K\n" +
	"\x16SearchProductsResponse\x121\n" +
	"\blistings\x18\x01 \x03(\v2\x15.search.v1.ListingHitR\blistings2f\n" +
	"\rSearchService\x12U\n" +
	"\x0eSearchProducts\x12 .search.v1.SearchProductsRequest\x1a!.search.v1.SearchProductsResponseBRZPgithub.com/phuchoang2603/refurbished-marketplace/shared/proto/search/v1;searchv1b\x06proto3"

var (
	file_shared_proto_search_v1_search_proto_rawDescOnce sync.Once
	file_shared_proto_search_v1_search_proto_rawDescData []byte
)

func file_shared_proto_search_v1_search_proto_rawDescGZIP() []byte {
	file_shared_proto_search_v1_search_proto_rawDescOnce.Do(func() {
		file_shared_proto_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_search_v1_search_proto_rawDesc), len(file_shared_proto_search_v1_search_proto_rawDesc)))
	})
	return file_shared_proto_search_v1_search_proto_rawDescData
}

var file_shared_proto_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shared_proto_search_v1_search_proto_goTypes = []any{
	(*SearchProductsRequest)(nil),  // 0: search.v1.SearchProductsRequest
	(*ListingHit)(nil),             // 1: search.v1.ListingHit
	(*SearchProductsResponse)(nil), // 2: search.v1.SearchProductsResponse
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_shared_proto_search_v1_search_proto_depIdxs = []int32{
	3, // 0: search.v1.ListingHit.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: search.v1.SearchProductsResponse.listings:type_name -> search.v1.ListingHit
	0, // 2: search.v1.SearchService.SearchProducts:input_type -> search.v1.SearchProductsRequest
	2, // 3: search.v1.SearchService.SearchProducts:output_type -> search.v1.SearchProductsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shared_proto_search_v1_search_proto_init() }
func file_shared_proto_search_v1_search_proto_init() {
	if File_shared_proto_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_search_v1_search_proto_rawDesc), len(file_shared_proto_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_search_v1_search_proto_goTypes,
		DependencyIndexes: file_shared_proto_search_v1_search_proto_depIdxs,
		MessageInfos:      file_shared_proto_search_v1_search_proto_msgTypes,
	}.Build()
	File_shared_proto_search_v1_search_proto = out.File
	file_shared_proto_search_v1_search_proto_goTypes = nil
	file_shared_proto_search_v1_search_proto_depIdxs = nil
}
