// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID          uuid.UUID
	BuyerUserID uuid.UUID
	Status      string
	TotalCents  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	MerchantID  uuid.UUID
}

type OrderItem struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	ProductID      uuid.UUID
	Quantity       int32
	UnitPriceCents int64
	LineTotalCents int64
	CreatedAt      time.Time
}

type OrdersOutbox struct {
	ID              uuid.UUID
	AggregateID     uuid.UUID
	EventType       string
	Payload         []byte
	PublishAttempts int32
	CreatedAt       time.Time
	PublishedAt     sql.NullTime
}
