// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID          uuid.UUID
	BuyerUserID uuid.UUID
	ProductID   uuid.UUID
	Quantity    int32
	Status      string
	TotalCents  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
