// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders-create.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, buyer_user_id, merchant_id, status, total_cents)
VALUES ($1, $2, $3, $4, $5)
RETURNING
    orders.id, orders.buyer_user_id, orders.status, orders.total_cents, orders.created_at, orders.updated_at, orders.merchant_id
`

type CreateOrderParams struct {
	ID          uuid.UUID
	BuyerUserID uuid.UUID
	MerchantID  uuid.UUID
	Status      string
	TotalCents  int64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.ID,
		arg.BuyerUserID,
		arg.MerchantID,
		arg.Status,
		arg.TotalCents,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BuyerUserID,
		&i.Status,
		&i.TotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MerchantID,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    id,
    order_id,
    product_id,
    quantity,
    unit_price_cents,
    line_total_cents
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    order_items.id, order_items.order_id, order_items.product_id, order_items.quantity, order_items.unit_price_cents, order_items.line_total_cents, order_items.created_at
`

type CreateOrderItemParams struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	ProductID      uuid.UUID
	Quantity       int32
	UnitPriceCents int64
	LineTotalCents int64
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.LineTotalCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.LineTotalCents,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderOutbox = `-- name: CreateOrderOutbox :one
INSERT INTO orders_outbox (id, aggregate_id, event_type, payload)
VALUES ($1, $2, $3, $4)
RETURNING
    orders_outbox.id, orders_outbox.aggregate_id, orders_outbox.event_type, orders_outbox.payload, orders_outbox.publish_attempts, orders_outbox.created_at, orders_outbox.published_at
`

type CreateOrderOutboxParams struct {
	ID          uuid.UUID
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
}

func (q *Queries) CreateOrderOutbox(ctx context.Context, arg CreateOrderOutboxParams) (OrdersOutbox, error) {
	row := q.db.QueryRowContext(ctx, createOrderOutbox,
		arg.ID,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	var i OrdersOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.PublishAttempts,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}
