// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders-read.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, buyer_user_id, status, total_cents, created_at, updated_at, merchant_id
FROM orders
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BuyerUserID,
		&i.Status,
		&i.TotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MerchantID,
	)
	return i, err
}

const listOrderItemsByOrderIDs = `-- name: ListOrderItemsByOrderIDs :many
SELECT id, order_id, product_id, quantity, unit_price_cents, line_total_cents, created_at
FROM order_items
WHERE order_id = ANY($1::uuid [])
ORDER BY order_id ASC, created_at ASC
`

func (q *Queries) ListOrderItemsByOrderIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrderIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.LineTotalCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByBuyer = `-- name: ListOrdersByBuyer :many
SELECT id, buyer_user_id, status, total_cents, created_at, updated_at, merchant_id
FROM orders
WHERE buyer_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByBuyerParams struct {
	BuyerUserID uuid.UUID
	Limit       int32
	Offset      int32
}

func (q *Queries) ListOrdersByBuyer(ctx context.Context, arg ListOrdersByBuyerParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByBuyer, arg.BuyerUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.BuyerUserID,
			&i.Status,
			&i.TotalCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MerchantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
