apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-root
spec:
  project: default
  source:
    repoURL: https://github.com/phuchoang2603/refurbished-marketplace.git
    targetRevision: main
    path: infra/argocd/staging/apps
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
