apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-root
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/phuchoang2603/refurbished-marketplace.git
    targetRevision: main
    path: infra/argocd/app-of-apps
    helm:
      values: |
        namePrefix: staging
        global:
          imageRegistry: ghcr.io/phuchoang2603/refurbished-marketplace
          imageTag: main
        marketplace:
          enabled: true
          valueFiles:
            - values-staging.yaml
        apps:
          external-secrets:
            valueFiles:
              - values-staging.yaml
          cnpg:
            valueFiles:
              - values-staging.yaml
          strimzi:
            valueFiles:
              - values-staging.yaml
          istiod:
            valueFiles:
              - values-staging.yaml
          istio-cni:
            valueFiles:
              - values-staging.yaml
          ztunnel:
            valueFiles:
              - values-staging.yaml
          observability:
            valueFiles:
              - values-staging.yaml
          kafka:
            valueFiles:
              - values-staging.yaml
          cloudflare-tunnel:
            valueFiles:
              - values-staging.yaml
      parameters:
        - name: targetRevision
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
