// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Checkout struct {
	ID               uuid.UUID
	BuyerUserID      uuid.UUID
	MerchantID       uuid.UUID
	IntentKey        string
	RequestHash      []byte
	Snapshot         json.RawMessage
	State            string
	Version          int64
	OrderID          uuid.NullUUID
	PaymentSessionID sql.NullString
	PaymentReturnUrl sql.NullString
	FailureReason    sql.NullString
	DeadlineAt       sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type CheckoutException struct {
	ID         uuid.UUID
	CheckoutID uuid.UUID
	MessageID  sql.NullString
	Kind       string
	Details    string
	ResolvedAt sql.NullTime
	CreatedAt  time.Time
}

type CheckoutInbox struct {
	MessageID  string
	CheckoutID uuid.UUID
	ReceivedAt time.Time
}

type CheckoutOutbox struct {
	ID                 uuid.UUID
	AggregateID        uuid.UUID
	EventType          string
	Payload            []byte
	Tracingspancontext sql.NullString
	CreatedAt          time.Time
}
