apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-kafka
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/phuchoang2603/refurbished-marketplace.git
    targetRevision: istio-observe-baseline
    path: infra/charts/kafka
    helm:
      releaseName: ecommerce-kafka-cluster
      values: |
        global:
          imageRegistry: ghcr.io/phuchoang2603/refurbished-marketplace
          imageTag: main
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
