apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-kafka
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/phuchoang2603/refurbished-marketplace.git
    targetRevision: main
    path: infra/charts/kafka
    helm:
      releaseName: ecommerce-kafka-cluster
      values: |
        global:
          imageRegistry: ghcr.io/phuchoang2603/refurbished-marketplace
          imageTag: main

        entities:
          orders:
            connector:
              name: orders-outbox
              sourceSecretName: orders-app
              databaseName: orders_db
              databaseHost: orders-db-rw
              databasePort: 5432
              outboxTable: public.orders_outbox
          payment:
            connector:
              name: payment-outbox
              sourceSecretName: payment-app
              databaseName: payment_db
              databaseHost: payment-db-rw
              databasePort: 5432
              outboxTable: public.payment_outbox
          inventory:
            connector:
              name: inventory-outbox
              sourceSecretName: products-app
              databaseName: products_db
              databaseHost: products-db-rw
              databasePort: 5432
              outboxTable: public.inventory_outbox

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
