apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-cnpg
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/phuchoang2603/refurbished-marketplace.git
    targetRevision: add-istio-ingress
    path: infra/charts/operators/cnpg
    helm:
      releaseName: cnpg
  destination:
    server: https://kubernetes.default.svc
    namespace: operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
