global:
  imagePullPolicy: IfNotPresent

services:
  web:
    enabled: true
    image: refurbished-marketplace/web
    port: 8080
    auth:
      secretName: users-auth
      secretKey: JWT_SECRET
    env:
      USERS_SVC_ADDR: users:9091
      PRODUCTS_SVC_ADDR: products:9092
      ORDERS_SVC_ADDR: orders:9093
      CART_SVC_ADDR: cart:9094

  users:
    enabled: true
    image: refurbished-marketplace/users
    port: 9091
    auth:
      secretName: users-auth
      secretKey: JWT_SECRET
    migration:
      enabled: true
      image: refurbished-marketplace/users-migrator
    db:
      host: users-db-rw
      port: 5432
      name: users_db
      owner: users_app
      secretName: users-app
      usernameKey: username
      passwordKey: password
      instances: 1
      storageSize: 1Gi

  products:
    enabled: true
    image: refurbished-marketplace/products
    port: 9092
    migration:
      enabled: true
      image: refurbished-marketplace/products-migrator
    db:
      host: products-db-rw
      port: 5432
      name: products_db
      owner: products_app
      secretName: products-app
      usernameKey: username
      passwordKey: password
      instances: 1
      storageSize: 1Gi

  orders:
    enabled: true
    image: refurbished-marketplace/orders
    port: 9093
    migration:
      enabled: true
      image: refurbished-marketplace/orders-migrator
    db:
      host: orders-db-rw
      port: 5432
      name: orders_db
      owner: orders_app
      secretName: orders-app
      usernameKey: username
      passwordKey: password
      instances: 1
      storageSize: 1Gi

  cart:
    enabled: true
    image: refurbished-marketplace/cart
    port: 9094
    env:
      REDIS_ADDR: cache:6379

cache:
  enabled: true
  image: docker.io/valkey/valkey:7.2.5
  port: 6379
  instances: 1
