global:
  imagePullPolicy: IfNotPresent

services:
  web:
    enabled: true
    image: refurbished-marketplace/web
    port: 8080
    env:
      USERS_GRPC_ADDR: users:9091
      PRODUCTS_SVC_ADDR: products:8082
      ORDERS_SVC_ADDR: orders:8083
  users:
    enabled: true
    image: refurbished-marketplace/users
    port: 9091
    auth:
      secretName: users-auth
      secretKey: JWT_SECRET
    migration:
      enabled: true
      image: refurbished-marketplace/users-migrator
    db:
      host: users-db-rw
      port: 5432
      name: users_db
      secretName: users-app
      usernameKey: username
      passwordKey: password
  products:
    enabled: true
    image: refurbished-marketplace/products
    port: 8082
    migration:
      enabled: false
      image: ghcr.io/kukymbr/goose-docker:3.27.0
    db:
      host: products-db-rw
      port: 5432
      name: products_db
      secretName: products-app
      usernameKey: username
      passwordKey: password
  orders:
    enabled: true
    image: refurbished-marketplace/orders
    port: 8083
    migration:
      enabled: false
      image: ghcr.io/kukymbr/goose-docker:3.27.0
    db:
      host: orders-db-rw
      port: 5432
      name: orders_db
      secretName: orders-app
      usernameKey: username
      passwordKey: password

databases:
  users:
    enabled: true
    dbName: users_db
    owner: users_app
    appSecretName: users-app
    instances: 1
    storage:
      size: 1Gi
  products:
    enabled: true
    dbName: products_db
    owner: products_app
    appSecretName: products-app
    instances: 1
    storage:
      size: 1Gi
  orders:
    enabled: true
    dbName: orders_db
    owner: orders_app
    appSecretName: orders-app
    instances: 1
    storage:
      size: 1Gi
