apiVersion: v1
kind: Secret
metadata:
  name: users-app
  namespace: ecommerce
type: kubernetes.io/basic-auth
stringData:
  username: users_app
  password: users_app_dev_password
---
apiVersion: v1
kind: Secret
metadata:
  name: products-app
  namespace: ecommerce
type: kubernetes.io/basic-auth
stringData:
  username: products_app
  password: products_app_dev_password
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-app
  namespace: ecommerce
type: kubernetes.io/basic-auth
stringData:
  username: orders_app
  password: orders_app_dev_password
---
apiVersion: v1
kind: Secret
metadata:
  name: users-auth
  namespace: ecommerce
type: Opaque
stringData:
  JWT_SECRET: dev-jwt-secret
