// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createInventoryReservation = `-- name: CreateInventoryReservation :one
INSERT INTO inventory_reservations (order_id, product_id, quantity, status)
VALUES ($1, $2, $3, $4)
RETURNING inventory_reservations.order_id, inventory_reservations.product_id, inventory_reservations.quantity, inventory_reservations.status, inventory_reservations.created_at, inventory_reservations.updated_at
`

type CreateInventoryReservationParams struct {
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	Status    string
}

func (q *Queries) CreateInventoryReservation(ctx context.Context, arg CreateInventoryReservationParams) (InventoryReservation, error) {
	row := q.db.QueryRowContext(ctx, createInventoryReservation,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Status,
	)
	var i InventoryReservation
	err := row.Scan(
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveInventoryReservationsByOrderID = `-- name: ListActiveInventoryReservationsByOrderID :many
SELECT order_id, product_id, quantity, status, created_at, updated_at
FROM inventory_reservations
WHERE order_id = $1 AND status = 'RESERVED'
ORDER BY product_id
FOR UPDATE
`

func (q *Queries) ListActiveInventoryReservationsByOrderID(ctx context.Context, orderID uuid.UUID) ([]InventoryReservation, error) {
	rows, err := q.db.QueryContext(ctx, listActiveInventoryReservationsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryReservation
	for rows.Next() {
		var i InventoryReservation
		if err := rows.Scan(
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryReservationsByOrderID = `-- name: ListInventoryReservationsByOrderID :many
SELECT order_id, product_id, quantity, status, created_at, updated_at
FROM inventory_reservations
WHERE order_id = $1
ORDER BY product_id
`

func (q *Queries) ListInventoryReservationsByOrderID(ctx context.Context, orderID uuid.UUID) ([]InventoryReservation, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryReservationsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryReservation
	for rows.Next() {
		var i InventoryReservation
		if err := rows.Scan(
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInventoryReservationCommitted = `-- name: MarkInventoryReservationCommitted :one
UPDATE inventory_reservations
SET
    status = 'COMMITTED',
    updated_at = NOW()
WHERE
    order_id = $1
    AND product_id = $2
    AND status = 'RESERVED'
RETURNING inventory_reservations.order_id, inventory_reservations.product_id, inventory_reservations.quantity, inventory_reservations.status, inventory_reservations.created_at, inventory_reservations.updated_at
`

type MarkInventoryReservationCommittedParams struct {
	OrderID   uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) MarkInventoryReservationCommitted(ctx context.Context, arg MarkInventoryReservationCommittedParams) (InventoryReservation, error) {
	row := q.db.QueryRowContext(ctx, markInventoryReservationCommitted, arg.OrderID, arg.ProductID)
	var i InventoryReservation
	err := row.Scan(
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markInventoryReservationReleased = `-- name: MarkInventoryReservationReleased :one
UPDATE inventory_reservations
SET
    status = 'RELEASED',
    updated_at = NOW()
WHERE
    order_id = $1
    AND product_id = $2
    AND status = 'RESERVED'
RETURNING inventory_reservations.order_id, inventory_reservations.product_id, inventory_reservations.quantity, inventory_reservations.status, inventory_reservations.created_at, inventory_reservations.updated_at
`

type MarkInventoryReservationReleasedParams struct {
	OrderID   uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) MarkInventoryReservationReleased(ctx context.Context, arg MarkInventoryReservationReleasedParams) (InventoryReservation, error) {
	row := q.db.QueryRowContext(ctx, markInventoryReservationReleased, arg.OrderID, arg.ProductID)
	var i InventoryReservation
	err := row.Scan(
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
