-- +goose Up
ALTER TABLE products
    ADD COLUMN IF NOT EXISTS terminal_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    ADD COLUMN IF NOT EXISTS x_pos DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS y_pos DOUBLE PRECISION NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE products
    DROP COLUMN IF EXISTS y_pos,
    DROP COLUMN IF EXISTS x_pos,
    DROP COLUMN IF EXISTS terminal_id;
