// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package input

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "strings"
import templpkg "github.com/a-h/templ"

func Input(args InputArgs) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		classes := inputVariants(args.Class)
		inputAttrs := make(templpkg.Attributes)

		for k, v := range args.Attributes {
			inputAttrs[k] = v
		}

		inputAttrs["data-slot"] = "input"
		inputAttrs["class"] = classes

		if args.Type != "" {
			inputAttrs["type"] = args.Type
		}
		if args.Placeholder != "" {
			inputAttrs["placeholder"] = args.Placeholder
		}
		if args.Value != "" {
			inputAttrs["value"] = args.Value
		}
		if args.Name != "" {
			inputAttrs["name"] = args.Name
		}
		if args.ID != "" {
			inputAttrs["id"] = args.ID
		}
		if args.Autocomplete != "" {
			inputAttrs["autocomplete"] = args.Autocomplete
		}
		if args.Min != "" {
			inputAttrs["min"] = args.Min
		}
		if args.Disabled {
			inputAttrs["disabled"] = true
		}
		if args.Required {
			inputAttrs["required"] = true
		}

		if args.FormID != "" && args.Name != "" {
			signalName := strings.ReplaceAll(args.FormID, "-", "_")
			inputAttrs["data-bind"] = signalName + "." + args.Name
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, inputAttrs)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
