// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkout.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countCheckoutCallbacks = `-- name: CountCheckoutCallbacks :one
SELECT count(*) FROM payment_checkout_callbacks WHERE order_id = $1
`

func (q *Queries) CountCheckoutCallbacks(ctx context.Context, orderID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCheckoutCallbacks, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCheckoutPaymentSession = `-- name: GetCheckoutPaymentSession :one
SELECT order_id, checkout_id, request_hash, create_operation_id, create_version, status, created_at FROM payment_checkout_sessions WHERE order_id = $1
`

func (q *Queries) GetCheckoutPaymentSession(ctx context.Context, orderID uuid.UUID) (PaymentCheckoutSession, error) {
	row := q.db.QueryRowContext(ctx, getCheckoutPaymentSession, orderID)
	var i PaymentCheckoutSession
	err := row.Scan(
		&i.OrderID,
		&i.CheckoutID,
		&i.RequestHash,
		&i.CreateOperationID,
		&i.CreateVersion,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertCheckoutCallback = `-- name: InsertCheckoutCallback :execrows
INSERT INTO payment_checkout_callbacks (order_id, outcome)
VALUES ($1, $2) ON CONFLICT (order_id, outcome) DO NOTHING
`

type InsertCheckoutCallbackParams struct {
	OrderID uuid.UUID
	Outcome string
}

func (q *Queries) InsertCheckoutCallback(ctx context.Context, arg InsertCheckoutCallbackParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCheckoutCallback, arg.OrderID, arg.Outcome)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertCheckoutPaymentSession = `-- name: InsertCheckoutPaymentSession :exec
INSERT INTO payment_checkout_sessions (order_id, checkout_id, request_hash, create_operation_id, create_version, status)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCheckoutPaymentSessionParams struct {
	OrderID           uuid.UUID
	CheckoutID        uuid.UUID
	RequestHash       []byte
	CreateOperationID uuid.NullUUID
	CreateVersion     sql.NullInt64
	Status            string
}

func (q *Queries) InsertCheckoutPaymentSession(ctx context.Context, arg InsertCheckoutPaymentSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertCheckoutPaymentSession,
		arg.OrderID,
		arg.CheckoutID,
		arg.RequestHash,
		arg.CreateOperationID,
		arg.CreateVersion,
		arg.Status,
	)
	return err
}
