// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_inbox_outbox.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPaymentOutbox = `-- name: CreatePaymentOutbox :one
INSERT INTO payment_outbox (
    id, aggregate_id, event_type, payload, tracingspancontext
)
VALUES ($1, $2, $3, $4, $5)
RETURNING
    payment_outbox.id, payment_outbox.aggregate_id, payment_outbox.event_type, payment_outbox.payload, payment_outbox.publish_attempts, payment_outbox.created_at, payment_outbox.published_at, payment_outbox.tracingspancontext
`

type CreatePaymentOutboxParams struct {
	ID                 uuid.UUID
	AggregateID        uuid.UUID
	EventType          string
	Payload            []byte
	Tracingspancontext string
}

func (q *Queries) CreatePaymentOutbox(ctx context.Context, arg CreatePaymentOutboxParams) (PaymentOutbox, error) {
	row := q.db.QueryRowContext(ctx, createPaymentOutbox,
		arg.ID,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Tracingspancontext,
	)
	var i PaymentOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.PublishAttempts,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Tracingspancontext,
	)
	return i, err
}

const insertPaymentInboxMessage = `-- name: InsertPaymentInboxMessage :one
INSERT INTO payment_inbox (message_id)
VALUES ($1)
ON CONFLICT (message_id) DO NOTHING
RETURNING TRUE
`

func (q *Queries) InsertPaymentInboxMessage(ctx context.Context, messageID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, insertPaymentInboxMessage, messageID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
