// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_transactions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPaymentTransaction = `-- name: CreatePaymentTransaction :one
INSERT INTO payment_transactions (
    id,
    order_id,
    order_item_id,
    merchant_id,
    amount_cents,
    currency,
    status,
    idempotency_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (order_item_id) DO NOTHING
RETURNING
    id, order_id, order_item_id, merchant_id, amount_cents, currency, status, idempotency_key, gateway_transaction_id, failure_reason, created_at, updated_at
`

type CreatePaymentTransactionParams struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	OrderItemID    uuid.UUID
	MerchantID     uuid.UUID
	AmountCents    int64
	Currency       string
	Status         string
	IdempotencyKey string
}

func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, createPaymentTransaction,
		arg.ID,
		arg.OrderID,
		arg.OrderItemID,
		arg.MerchantID,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrderItemID,
		&i.MerchantID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.IdempotencyKey,
		&i.GatewayTransactionID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentTransactionByID = `-- name: GetPaymentTransactionByID :one
SELECT
    id,
    order_id,
    order_item_id,
    merchant_id,
    amount_cents,
    currency,
    status,
    idempotency_key,
    gateway_transaction_id,
    failure_reason,
    created_at,
    updated_at
FROM payment_transactions
WHERE id = $1
`

func (q *Queries) GetPaymentTransactionByID(ctx context.Context, id uuid.UUID) (PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, getPaymentTransactionByID, id)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrderItemID,
		&i.MerchantID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.IdempotencyKey,
		&i.GatewayTransactionID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentTransactionByOrderItemID = `-- name: GetPaymentTransactionByOrderItemID :one
SELECT
    id,
    order_id,
    order_item_id,
    merchant_id,
    amount_cents,
    currency,
    status,
    idempotency_key,
    gateway_transaction_id,
    failure_reason,
    created_at,
    updated_at
FROM payment_transactions
WHERE order_item_id = $1
`

func (q *Queries) GetPaymentTransactionByOrderItemID(ctx context.Context, orderItemID uuid.UUID) (PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, getPaymentTransactionByOrderItemID, orderItemID)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrderItemID,
		&i.MerchantID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.IdempotencyKey,
		&i.GatewayTransactionID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentTransactionGatewayResult = `-- name: UpdatePaymentTransactionGatewayResult :one
UPDATE payment_transactions
SET
    status = $2,
    gateway_transaction_id = $3,
    failure_reason = $4,
    updated_at = NOW()
WHERE id = $1 AND status NOT IN ('SUCCEEDED', 'FAILED')
RETURNING
    id, order_id, order_item_id, merchant_id, amount_cents, currency, status, idempotency_key, gateway_transaction_id, failure_reason, created_at, updated_at
`

type UpdatePaymentTransactionGatewayResultParams struct {
	ID                   uuid.UUID
	Status               string
	GatewayTransactionID sql.NullString
	FailureReason        sql.NullString
}

func (q *Queries) UpdatePaymentTransactionGatewayResult(ctx context.Context, arg UpdatePaymentTransactionGatewayResultParams) (PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentTransactionGatewayResult,
		arg.ID,
		arg.Status,
		arg.GatewayTransactionID,
		arg.FailureReason,
	)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrderItemID,
		&i.MerchantID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.IdempotencyKey,
		&i.GatewayTransactionID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
