apiVersion: v2
name: meilisearch
description: Meilisearch storefront catalog projection in ecommerce
type: application
version: 0.1.0
appVersion: "1.53.1"
dependencies:
  - name: meilisearch
    version: 0.24.2
    repository: https://meilisearch.github.io/meilisearch-kubernetes
